import { Component, ElementRef, OnDestroy, AfterViewInit, Output, EventEmitter, Input, Injector, input } from '@angular/core';
import { BaseComponent } from '@sharedcommon/base/base.component';
import { TimeConversionService } from '@sharedcommon/service/time-conversion.service';
import { create, createOptions, RichEdit, Interval, ViewType, RichEditUnit, DocumentFormat, Margins } from 'devexpress-richedit';
import {
  Options, RibbonTabType, FileTabItemId, HomeTabItemId, RibbonItem,
  RibbonSubMenuItem, RibbonMenuItem, RibbonButtonItem, FirstLevelRibbonItem, RibbonTab
} from 'devexpress-richedit';
import { CookieStorageService } from 'src/app/core/services/cookie-storage.service';
import { MasterEndpoint } from 'src/app/setup/endpoint/master.endpoint';

@Component({
  selector: 'app-devrich-printtemplates',
  templateUrl: './devrich-printtemplates.component.html',
  styleUrl: './devrich-printtemplates.component.scss'
})
export class DevrichPrinttemplatesComponent extends BaseComponent<any>{
  
  @Output() extractedContentChange = new EventEmitter<any>();
  @Output() fullscreenClicked = new EventEmitter<any>();

  @Input() content: any;
  @Input() rtf_content: any;
  @Input() loadRTF: boolean = false ;
  @Input() showHeader: boolean = false;
  @Input() patient: any ; 
  @Input() autoSave: boolean = false;

  private rich: RichEdit | null = null;

  settings: any = {
		header_height: 0,
		footer_height: 0,
		margin_left: 0,
		margin_right: 0,
		font: null
	};

  constructor(
    injector: Injector,
    private element: ElementRef,
    private masterEndpoint: MasterEndpoint,
    private cookieSrvc: CookieStorageService,
    private timeSrvc: TimeConversionService
  ) { super(injector) }

  override ngOnDestroy() {
    if (this.rich) {
      this.rich.dispose();
      this.rich = null;
    }
  }

  override ngOnInit(): void {
    this.subsink.sink = this.masterEndpoint.getLetterHeadSetting(this.cookieSrvc.getCookieData().client_id).subscribe((set: any) => {
      this.settings.header_height = set[0].header_height;
      this.settings.footer_height = set[0].footer_height;
      this.settings.margin_left = set[0].margin_left;
      this.settings.margin_right = set[0].margin_right;
      this.setContent();
    });

  }

  override ngAfterViewInit(): void {
   

  }

  setContent(){
     // the createOptions() method creates an object that contains RichEdit options initialized with default values
     const options = createOptions();

     this.ribbonCustomization(options)
 
     options.unit = RichEditUnit.Centimeter;
     options.view!.viewType = ViewType.PrintLayout;
     options.events.saving = (e) => { this.saveReport() };
     options.events.saved = (e) => {  };

     if(this.autoSave){
      options.events.documentChanged = (e) =>{
        this.saveReport()
       }
     }


     // capitalize the first letter at the beginning of a new sentence/line
     options.events.autoCorrect = function (s, e) {
       if (e.text.length == 1 && /\w/.test(e.text)) {
         var prevText = s.document.getText(new Interval(e.interval.start - 2, 2));
         if (prevText.length == 0 || /^(\. |\? |\! )$/.test(prevText) || prevText.charCodeAt(1) == 13) {
           var newText = e.text.toUpperCase();
           if (newText != e.text) {
             s.beginUpdate();
             s.history.beginTransaction();
             s.document.deleteText(e.interval);
             s.document.insertText(e.interval.start, newText);
             s.history.endTransaction();
             s.endUpdate();
             e.handled = true;
           }
         }
       }
     };
 
     options.readOnly = false;
     options.width = '100%';
     options.height = '80vh';
 
     this.rich = create(this.element.nativeElement.firstElementChild, options);
 
     var blankDocument = "e1xydGYxXGRlZmYwe1xmb250dGJse1xmMCBDYWxpYnJpO319e1xjb2xvcnRibCA7XHJlZDBcZ3JlZW4wXGJsdWUyNTUgO317XCpcZGVmY2hwIFxmczIyfXtcc3R5bGVzaGVldCB7XHFsXGZzMjIgTm9ybWFsO317XCpcY3MxXGZzMjIgRGVmYXVsdCBQYXJhZ3JhcGggRm9udDt9e1wqXGNzMlx1bFxmczIyXGNmMSBIeXBlcmxpbms7fXtcKlx0czNcdHNyb3dkXGZzMjJccWxcdHN2ZXJ0YWx0XGNsdHhscnRiIE5vcm1hbCBUYWJsZTt9fXtcKlxsaXN0b3ZlcnJpZGV0YWJsZX17XGluZm99XG5vdWljb21wYXRcc3BseXR3bmluZVxodG1hdXRzcFxleHBzaHJ0blxzcGx0cGdwYXJcZGVmdGFiNzIwXHNlY3RkXG1hcmdsc3huMTQ0MFxtYXJncnN4bjE0NDBcbWFyZ3RzeG4xNDQwXG1hcmdic3huMTQ0MFxoZWFkZXJ5NzIwXGZvb3Rlcnk3MjBccGd3c3huMTIyNDBccGdoc3huMTU4NDBcY29sczFcY29sc3g3MjBccGFyZFxwbGFpblxxbFxmczIyXGNmMFxwYXJ9"
 
     if(this.showHeader){
      try{
        this.rich.openDocument(this.blankDocumentWithHeader, "DocumentName", DocumentFormat.Rtf);
      }catch(error){
        this.rich.openDocument(blankDocument, "DocumentName", DocumentFormat.Rtf);
      }

     }else{
       this.rich.openDocument(blankDocument, "DocumentName", DocumentFormat.Rtf);
     }

     if(true){
      setTimeout(()=>{
        this.setMargins(null);
     },1000)
     }
  
  }


  setRtfHeader(patient: any = this.patient){
      this.blankDocumentWithHeader = this.changeRtf(this.blankDocumentWithHeader, patient?.LabPatientTestID?.patient?.name, "\\{PATIENTNAME\\}");
      this.blankDocumentWithHeader = this.changeRtf(this.blankDocumentWithHeader, patient?.LabPatientTestID?.patient?.title, "\\{TITLE\\}");
      this.blankDocumentWithHeader = this.changeRtf(this.blankDocumentWithHeader, patient.LabPatientTestID?.patient.gender, "\\{GENDER\\}")
      this.blankDocumentWithHeader = this.changeRtf(this.blankDocumentWithHeader, patient?.LabPatientTestID?.patient?.ULabPatientAge == 'DOB' ? patient?.LabPatientTestID?.patient?.dob : patient?.LabPatientTestID?.patient?.age , "\\{AGE\\}")
      this.blankDocumentWithHeader = this.changeRtf(this.blankDocumentWithHeader, patient.LabPatientTestID?.patient?.referral_doctor ? patient.LabPatientTestID?.patient?.referral_doctor : 'SELF', "\\{REFERRALDOCTOR\\}");

      this.blankDocumentWithHeader = this.changeRtf(this.blankDocumentWithHeader, patient.LabPatientTestID?.patient?.visit_id, "\\{VISITID\\}");

      this.blankDocumentWithHeader = this.changeRtf(this.blankDocumentWithHeader, this.timeSrvc.decodeTimestamp(patient.LabPatientTestID?.patient?.added_on, true), "\\{REGDATE\\}");
  }
  
  
  private setMargins(headerText: string | null): void {

    var documentSection = this.rich!.document.sections.getByIndex(0);

    var marginSizeTop = this.rich!.unitConverter.pixelsToTwips(parseInt(this.settings.header_height));
    var marginSizeFooter = this.rich!.unitConverter.pixelsToTwips(parseInt(this.settings.footer_height));
    var marginSizeLeft = this.rich!.unitConverter.pixelsToTwips(parseInt(this.settings.margin_left));
    var marginSizeRight = this.rich!.unitConverter.pixelsToTwips(parseInt(this.settings.margin_right));

    documentSection!.headerOffset = marginSizeTop;
    this.rich!.document.sections.getByIndex(0)!.margins = new Margins(marginSizeLeft, marginSizeRight, 0, marginSizeFooter )

    if(headerText){
      this.rich!.beginUpdate();
      this.rich!.history.beginTransaction();
  
      this.rich?.document.subDocuments.main.insertRtf(-1,headerText)
  
      this.rich!.history.endTransaction();
      this.rich!.endUpdate();
    }


  }

  removeTabs(options: Options) {
    // remove items
    const fileTab: any = options.ribbon.getTab(RibbonTabType.File);
    const PageLayout: any = options.ribbon.getTab(RibbonTabType.PageLayout);
    const mailMerge: any = options.ribbon.getTab(RibbonTabType.MailMerge);
    const viewTab: any = options.ribbon.getTab(RibbonTabType.View);
    // fileTab!.removeItem(FileTabItemId.OpenDocument);

    // options.ribbon.removeTab(fileTab);
    
    options.ribbon.removeTab(mailMerge);
    // options.ribbon.removeTab(PageLayout);
    options.ribbon.removeTab(viewTab);

  }


  ribbonCustomization(options: Options) {

    this.removeTabs(options)

    const homeTab = options.ribbon.getTab(RibbonTabType.Home);
    homeTab!.removeItem(HomeTabItemId.Copy);
    homeTab!.removeItem(HomeTabItemId.Cut);
    homeTab!.removeItem(HomeTabItemId.Paste);

    // move items to new tab
    const findElem: RibbonItem = homeTab!.getItem(HomeTabItemId.Find)!;
    const replaceElem: RibbonItem = homeTab!.getItem(HomeTabItemId.Replace)!;
    homeTab!.removeItem(findElem);
    homeTab!.removeItem(replaceElem);

    // remove tab
    options.ribbon.removeTab(RibbonTabType.References);

  }


  saveReport(saveRpt: boolean = true){

    if(this.rich){
      this.rich!.exportToFile((e: any) => {
  
        if (e instanceof Blob) {
            const reader = new FileReader();
            reader.onload = () => {
              const rtfContent = reader.result as string;
              this.emitExtractedContent(rtfContent, saveRpt)
            };
            reader.readAsText(e);
          } else if (e.blob instanceof Blob) {
            const reader = new FileReader();
          reader.onload = () => {
            const rtfContent = reader.result as string;
            this.emitExtractedContent(rtfContent, saveRpt)
          };
          reader.readAsText(e.blob);
        }
      }, DocumentFormat.Rtf);
    }
    
  }


  fullscreen(){
    this.rich!.exportToFile((e: any) => {
  
      if (e instanceof Blob) {
        const reader = new FileReader();
        reader.onload = () => {
          const rtfContent = reader.result as string;
          this.fullscreenClicked.emit({  rtf_content: rtfContent });
        };
        reader.readAsText(e);
      } else if (e.blob instanceof Blob) {
        const reader = new FileReader();
        reader.onload = () => {
          const rtfContent = reader.result as string;
          this.fullscreenClicked.emit({  rtf_content: rtfContent });
        };
        reader.readAsText(e.blob);
      }
    }, DocumentFormat.Rtf);


  }

  getHtml(){
    const blackouts = document.querySelectorAll('.dxreBlackout') as any;
    blackouts.forEach((element : any)=>{
      element.remove();
    });

    const elements = document.querySelectorAll('.dxrePageArea') as any;

    let mergedHtml = '';
    let index = 0 ;

    elements.forEach((element: any) => {

        element.style.top = '';
        element.style.left = '';
        mergedHtml += element.outerHTML;

        if (index < elements.length - 1) {
          mergedHtml += "<div class='break_page'></div>";
        }
        
        index++
    });

    return mergedHtml
  }


  emitExtractedContent(content: any, e: boolean) {
		this.extractedContentChange.emit({ rtf_content: this.rtfToBase64(content), saveClose : e});
	};


  file: any = `
 e1xydGYxXGRlZmYwe1xmb250dGJse1xmMCBDYWxpYnJpO317XGYxIFRpbWVzIE5ldyBSb21hbjt9e1xmMiBBcmlhbDt9fXtcY29sb3J0YmwgO1xyZWQwXGdyZWVuMFxibHVlMjU1IDtccmVkMFxncmVlbjBcYmx1ZTAgO317XCpcZGVmY2hwIFxmczIyfXtcc3R5bGVzaGVldCB7XHFsXGZzMjIgTm9ybWFsO317XCpcY3MxXGZzMjIgRGVmYXVsdCBQYXJhZ3JhcGggRm9udDt9e1wqXGNzMlxmczIyXGNmMSBIeXBlcmxpbms7fXtcKlx0czNcdHNyb3dkXGZzMjJccWxcdHN2ZXJ0YWx0XGNsdHhscnRiIE5vcm1hbCBUYWJsZTt9fXtcKlxsaXN0b3ZlcnJpZGV0YWJsZX17XGluZm99XG5vdWljb21wYXRcc3BseXR3bmluZVxodG1hdXRzcFxleHBzaHJ0blxzcGx0cGdwYXJcZGVmdGFiNzIwXHNlY3RkXG1hcmdsc3huMTQ0MFxtYXJncnN4bjE0NDBcbWFyZ3RzeG4xNDQwXG1hcmdic3huMTQ0MFxoZWFkZXJ5NzIwXGZvb3Rlcnk3MjBccGd3c3huMTIyNDBccGdoc3huMTU4NDBcY29sczFcY29sc3g3MjBccGFyZFxwbGFpblxxY3tcYlxmMVxmczI2XGNmMCAgICAgICAgfXtcYlxmMVxmczI4XGNmMCAgICAgfXtcYlx1bFxmMlxmczI4XGNmMiBVTFRSQVNPTk9HUkFNIE9GIFRIRSBBQkRPTUVOICYgUEVMVklTfVxmczIyXGNmMFxwYXJccGFyZFxwbGFpblxxY3tcZjJcZnMyNlxjZjAgIH1cZnMyMlxjZjBccGFyXHBhcmRccGxhaW5ccWxcZmktMjA3MFxsaTIwNzBcbGluMjA3MHtcYlxmMlxmczI2XGNmMCBMSVZFUn17XGYyXGZzMjZcY2YwIFx0YWIgIFx0YWIgIFx0YWIgTm9ybWFsIGluIHNpemUgd2l0aCBub3JtYWwgZWNob3RleHR1cmUufVxmczIyXGNmMFxwYXJccGFyZFxwbGFpblxxbFxsaTIwNzBcbGluMjA3MHtcZjJcZnMyNlxjZjAgICAgXHRhYiBObyBpbnRyYSBvciBleHRyYSBoZXBhdGljIGJpbGlhcnkgZHVjdCBkaWxhdGF0aW9uLiAgfVxmczIyXGNmMFxwYXJccGFyZFxwbGFpblxxbHtcZjJcZnMyNlxjZjAgXHRhYiAgXHRhYiBcdGFiICBcdGFiIENCRCAmIFBvcnRhbCB2ZWluIGFyZSBub3JtYWwufVxmczIyXGNmMFxwYXJccGFyZFxwbGFpblxxbHtcZjJcZnMyNlxjZjAgIH1cZnMyMlxjZjBccGFyXHBhcmRccGxhaW5ccWx7XGJcZjJcZnMyNlxjZjAgR0FMTCBCTEFEREVSfXtcZjJcZnMyNlxjZjAgXHRhYiAgIFx0YWIgUGh5c2lvbG9naWNhbGx5IGRpc3RlbmRlZCBhbmQgc2hvd3Mgbm8gZXZpZGVuY2V9XGZzMjJcY2YwXHBhclxwYXJkXHBsYWluXHFse1xmMlxmczI2XGNmMCBcdGFiIFx0YWIgIFx0YWIgIFx0YWIgb2YgY2FsY3VsaSAvIGluZmxhbW1hdG9yeSBjaGFuZ2VzIC8gbWFzcyBsZXNpb24ufVxmczIyXGNmMFxwYXJccGFyZFxwbGFpblxxbHtcZjJcZnMyNlxjZjAgIH1cZnMyMlxjZjBccGFyXHBhcmRccGxhaW5ccWx7XGJcZjJcZnMyNlxjZjAgUEFOQ1JFQVN9e1xmMlxmczI2XGNmMCBcdGFiICAgICBcdGFiIEhlYWQsIGJvZHksIHZpc3VhbGl6ZWQgcGFydHMgb2YgdGFpbCBhcmUgbm9ybWFsLn1cZnMyMlxjZjBccGFyXHBhcmRccGxhaW5ccWx7XGYyXGZzMjZcY2YwICB9XGZzMjJcY2YwXHBhclxwYXJkXHBsYWluXHFse1xiXGYyXGZzMjZcY2YwIFNQTEVFTlx0YWIgfXtcZjJcZnMyNlxjZjAgXHRhYiAgICAgXHRhYiBOb3JtYWwgaW4gaXRzIHNpemUsIHNoYXBlIGFuZCBlY2hvdGV4dHVyZS59XGZzMjJcY2YwXHBhclxwYXJkXHBsYWluXHFse1xiXGYyXGZzMjZcY2YwICB9XGZzMjJcY2YwXHBhclxwYXJkXHBsYWluXHFse1xiXGYyXGZzMjZcY2YwIFJJR0hUIEtJRE5FWX17XGYyXGZzMjZcY2YwIFx0YWIgIFx0YWIgU2l6ZSAgOiBtbSB9XGZzMjJcY2YwXHBhclxwYXJkXHBsYWluXHFsXGZpNzIwXGxpMTQ0MFxsaW4xNDQwe1xmMlxmczI2XGNmMCAgXHRhYiBSaWdodCBraWRuZXkgaXMgbm9ybWFsIGluIHNpemUsIHNoYXBlIGFuZCBlY2hvdGV4dHVyZS59XGZzMjJcY2YwXHBhclxwYXJkXHBsYWluXHFse1xmMlxmczI2XGNmMCBcdGFiIFx0YWIgIFx0YWIgICBcdGFiIENvbGxlY3Rpbmcgc3lzdGVtIGlzIG5vcm1hbC4gTm8gZXZpZGVuY2Ugb2YgY2FsY3VsaS59XGZzMjJcY2YwXHBhclxwYXJkXHBsYWluXHFse1xmMlxmczI2XGNmMCAgICB9XGZzMjJcY2YwXHBhclxwYXJkXHBsYWluXHFse1xiXGYyXGZzMjZcY2YwIExFRlQgS0lETkVZfXtcZjJcZnMyNlxjZjAgXHRhYiAgICBcdGFiIFNpemUgIDogIG1tfVxmczIyXGNmMFxwYXJccGFyZFxwbGFpblxxbHtcZjJcZnMyNlxjZjAgXHRhYiBcdGFiIFx0YWIgICAgICBcdGFiIExlZnQgIGtpZG5leSBpcyBub3JtYWwgaW4gc2l6ZSwgc2hhcGUgYW5kIGVjaG90ZXh0dXJlLn1cZnMyMlxjZjBccGFyXHBhcmRccGxhaW5ccWx7XGYyXGZzMjZcY2YwIFx0YWIgXHRhYiBcdGFiICAgICAgXHRhYiBDb2xsZWN0aW5nIHN5c3RlbSBpcyBub3JtYWwuIE5vIGV2aWRlbmNlIG9mIGNhbGN1bGkufVxmczIyXGNmMFxwYXJccGFyZFxwbGFpblxxbHtcYlxmMlxmczI2XGNmMCAgfVxmczIyXGNmMFxwYXJccGFyZFxwbGFpblxxbHtcYlxmMlxmczI2XGNmMCBVUklOQVJZIEJMQURERVJ9e1xmMlxmczI2XGNmMCAgICAgIE5vcm1hbC4gTm8gY2FsY3VsaS5cdGFiICB9XGZzMjJcY2YwXHBhclxwYXJkXHBsYWluXHFse1xmMlxmczI2XGNmMCAgfVxmczIyXGNmMFxwYXJccGFyZFxwbGFpblxxbHtcYlxmMlxmczI2XGNmMCBQUk9TVEFURX17XGYyXGZzMjZcY2YwIFx0YWIgIFx0YWIgICAgXHRhYiBTaXplIDogIG1tICggVm9sdW1lIFx0YWIgY2MgKX1cZnMyMlxjZjBccGFyXHBhcmRccGxhaW5ccWx7XGYyXGZzMjZcY2YwIFx0YWIgXHRhYiBcdGFiICBcdGFiIE5vcm1hbCBpbiBzaXplLn1cZnMyMlxjZjBccGFyXHBhcmRccGxhaW5ccWx7XGYyXGZzMjZcY2YwICB9XGZzMjJcY2YwXHBhclxwYXJkXHBsYWluXHFse1xmMlxmczI2XGNmMCBBb3J0YSBhbmQgSVZDIGFyZSBub3JtYWwuICBObyBseW1waGFkZW5vcGF0aHkuICBObyBhc2NpdGVzLn1cZnMyMlxjZjBccGFyXHBhcmRccGxhaW5ccWx7XGYyXGZzMjZcY2YwICB9XGZzMjJcY2YwXHBhclxwYXJkXHBsYWluXHFse1xmMlxmczI2XGNmMCAgfVxmczIyXGNmMFxwYXJccGFyZFxwbGFpblxxbHtcYlxmMlxmczI2XGNmMCBJTVBSRVNTSU9OIDpcdGFiICB9XGZzMjJcY2YwXHBhclxwYXJkXHBsYWluXHFse1xmMlxmczI2XGNmMCAgIH1cZnMyMlxjZjBccGFyXHBhcmRccGxhaW5ccWxcZnMyMlxjZjBccGFyXHBhcmRccGxhaW5ccWx7XGYyXGZzMjZcY2YwIEZvciBjbGluaWNhbCBjb3JyZWxhdGlvbi59XGZzMjJcY2YwXHBhclxwYXJkXHBsYWluXHFse1xmMlxmczI2XGNmMCAgfVxmczIyXGNmMFxwYXJccGFyZFxwbGFpblxxbFxmczIyXGNmMFxwYXJccGFyZFxwbGFpblxxbFxmczIyXGNmMFxwYXJccGFyZFxwbGFpblxxantcYlxmMlxmczIyXGNmMCBEci4gUy4gQWx0YWYgQWxpICBNLkQgICAgRHIuIFN5ZWQgTmF6aXlhICBNLkQsIERNUkUgICAgIERyLiBSLkFudXNoYSAgTURcdGFiICBEci4gTWFuYXNhIFJlZGR5ICBNLkR9XGZzMjJcY2YwXHBhclxwYXJkXHBsYWluXHFse1xmMlxmczIyXGNmMCAgICAgUmFkaW9sb2dpc3RcdGFiIFx0YWIgICBcdGFiIFJhZGlvbG9naXN0XHRhYiAgXHRhYiAgXHRhYiBSYWRpb2xvZ2lzdFx0YWIgIFx0YWIgICAgICAgICBSYWRpb2xvZ2lzdFx0YWIgIH1cZnMyMlxjZjBccGFyXHBhcmRccGxhaW5ccWxcZnMyMlxjZjBccGFyXHBhcmRccGxhaW5ccWxcZnMyMlxjZjBccGFyfQ==
  `

  // testfile 
//   blankDocumentWithHeader = `
// e1xydGYxXGRlZmYwe1xmb250dGJse1xmMCBDYWxpYnJpO317XGYxIEFyaWFsO319e1xjb2xvcnRibCA7XHJlZDBcZ3JlZW4wXGJsdWUyNTUgO317XCpcZGVmY2hwIFxmczIyfXtcc3R5bGVzaGVldCB7XHFsXGZzMjIgTm9ybWFsO317XCpcY3MxXGZzMjIgRGVmYXVsdCBQYXJhZ3JhcGggRm9udDt9e1wqXGNzMlx1bFxmczIyXGNmMSBIeXBlcmxpbms7fXtcKlx0czNcdHNyb3dkXGZzMjJccWxcdHN2ZXJ0YWx0XGNsdHhscnRiIE5vcm1hbCBUYWJsZTt9fXtcKlxsaXN0b3ZlcnJpZGV0YWJsZX17XGluZm99XG5vdWljb21wYXRcc3BseXR3bmluZVxodG1hdXRzcFxleHBzaHJ0blxzcGx0cGdwYXJcZGVmdGFiNzIwXHNlY3RkXG1hcmdsc3huMTQ0MFxtYXJncnN4bjE0NDBcbWFyZ3RzeG4xNDQwXG1hcmdic3huMTQ0MFxoZWFkZXJ5NzIwXGZvb3Rlcnk3MjBccGd3c3huMTIyNDBccGdoc3huMTU4NDBcY29sczFcY29sc3g3MjB7XGhlYWRlcnJcdHJvd2RcaXJvdzBcaXJvd2JhbmQwXHRybGVmdC00NVx0cmZ0c1dpZHRoM1x0cndXaWR0aDk2MzJcdGJsaW5kdHlwZTNcdGJsaW5kMFxjbHZlcnRhbGNcY2xicmRydFxicmRybm9uZVxjbGJyZHJsXGJyZHJub25lXGNsYnJkcmJcYnJkcm5vbmVcY2xicmRyclxicmRybm9uZVxjbHR4bHJ0YlxjbGZ0c1dpZHRoM1xjbHdXaWR0aDE4NDJcY2xwYWRmYjNcY2xwYWRiNDVcY2xwYWRmbDNcY2xwYWRsNDVcY2xwYWRmcjNcY2xwYWRyNDVcY2xwYWRmdDNcY2xwYWR0NDVcY2VsbHgtMzVcY2x2ZXJ0YWxjXGNsYnJkcnRcYnJkcm5vbmVcY2xicmRybFxicmRybm9uZVxjbGJyZHJiXGJyZHJub25lXGNsYnJkcnJcYnJkcm5vbmVcY2x0eGxydGJcY2xmdHNXaWR0aDNcY2x3V2lkdGgzNDUxXGNscGFkZmIzXGNscGFkYjQ1XGNscGFkZmwzXGNscGFkbDQ1XGNscGFkZnIzXGNscGFkcjQ1XGNscGFkZnQzXGNscGFkdDQ1XGNlbGx4LTI1XGNsdmVydGFsY1xjbGJyZHJ0XGJyZHJub25lXGNsYnJkcmxcYnJkcm5vbmVcY2xicmRyYlxicmRybm9uZVxjbGJyZHJyXGJyZHJub25lXGNsdHhscnRiXGNsZnRzV2lkdGgzXGNsd1dpZHRoMTUzNlxjbHBhZGZiM1xjbHBhZGI0NVxjbHBhZGZsM1xjbHBhZGw0NVxjbHBhZGZyM1xjbHBhZHI0NVxjbHBhZGZ0M1xjbHBhZHQ0NVxjZWxseC0xNVxjbHZlcnRhbGNcY2xicmRydFxicmRybm9uZVxjbGJyZHJsXGJyZHJub25lXGNsYnJkcmJcYnJkcm5vbmVcY2xicmRyclxicmRybm9uZVxjbHR4bHJ0YlxjbGZ0c1dpZHRoM1xjbHdXaWR0aDI4MDNcY2xwYWRmYjNcY2xwYWRiNDVcY2xwYWRmbDNcY2xwYWRsNDVcY2xwYWRmcjNcY2xwYWRyNDVcY2xwYWRmdDNcY2xwYWR0NDVcY2VsbHgtNVxwYXJkXHBsYWluXHFsXGludGJse1xiXGYxXGZzMjJcY2YwIE5BTUV9XGYxXGZzMjJcY2YwXGNlbGxccGFyZFxwbGFpblxxbFxpbnRibHtcZjFcZnMyMlxjZjAgOiBce1NoYWZpU2hhaWtcfSBce1BBVElFTlROQU1FXH19XGYxXGZzMjJcY2YwXGNlbGxccGFyZFxwbGFpblxxbFxpbnRibHtcYlxmMVxmczIyXGNmMCBSRUdOT31cZjFcZnMyMlxjZjBcY2VsbFxwYXJkXHBsYWluXHFsXGludGJse1xmMVxmczIyXGNmMCA6IFx7VklTSVRJRFx9fVxmMVxmczIyXGNmMFxjZWxsXHRyb3dkXGlyb3cwXGlyb3diYW5kMFx0cmxlZnQtNDVcdHJmdHNXaWR0aDNcdHJ3V2lkdGg5NjMyXHRibGluZHR5cGUzXHRibGluZDBcY2x2ZXJ0YWxjXGNsYnJkcnRcYnJkcm5vbmVcY2xicmRybFxicmRybm9uZVxjbGJyZHJiXGJyZHJub25lXGNsYnJkcnJcYnJkcm5vbmVcY2x0eGxydGJcY2xmdHNXaWR0aDNcY2x3V2lkdGgxODQyXGNscGFkZmIzXGNscGFkYjQ1XGNscGFkZmwzXGNscGFkbDQ1XGNscGFkZnIzXGNscGFkcjQ1XGNscGFkZnQzXGNscGFkdDQ1XGNlbGx4LTM1XGNsdmVydGFsY1xjbGJyZHJ0XGJyZHJub25lXGNsYnJkcmxcYnJkcm5vbmVcY2xicmRyYlxicmRybm9uZVxjbGJyZHJyXGJyZHJub25lXGNsdHhscnRiXGNsZnRzV2lkdGgzXGNsd1dpZHRoMzQ1MVxjbHBhZGZiM1xjbHBhZGI0NVxjbHBhZGZsM1xjbHBhZGw0NVxjbHBhZGZyM1xjbHBhZHI0NVxjbHBhZGZ0M1xjbHBhZHQ0NVxjZWxseC0yNVxjbHZlcnRhbGNcY2xicmRydFxicmRybm9uZVxjbGJyZHJsXGJyZHJub25lXGNsYnJkcmJcYnJkcm5vbmVcY2xicmRyclxicmRybm9uZVxjbHR4bHJ0YlxjbGZ0c1dpZHRoM1xjbHdXaWR0aDE1MzZcY2xwYWRmYjNcY2xwYWRiNDVcY2xwYWRmbDNcY2xwYWRsNDVcY2xwYWRmcjNcY2xwYWRyNDVcY2xwYWRmdDNcY2xwYWR0NDVcY2VsbHgtMTVcY2x2ZXJ0YWxjXGNsYnJkcnRcYnJkcm5vbmVcY2xicmRybFxicmRybm9uZVxjbGJyZHJiXGJyZHJub25lXGNsYnJkcnJcYnJkcm5vbmVcY2x0eGxydGJcY2xmdHNXaWR0aDNcY2x3V2lkdGgyODAzXGNscGFkZmIzXGNscGFkYjQ1XGNscGFkZmwzXGNscGFkbDQ1XGNscGFkZnIzXGNscGFkcjQ1XGNscGFkZnQzXGNscGFkdDQ1XGNlbGx4LTVccm93XHRyb3dkXGlyb3cxXGlyb3diYW5kMVx0cmxlZnQtNDVcdHJmdHNXaWR0aDNcdHJ3V2lkdGg5NjMyXHRibGluZHR5cGUzXHRibGluZDBcY2x2ZXJ0YWxjXGNsYnJkcnRcYnJkcm5vbmVcY2xicmRybFxicmRybm9uZVxjbGJyZHJiXGJyZHJub25lXGNsYnJkcnJcYnJkcm5vbmVcY2x0eGxydGJcY2xmdHNXaWR0aDNcY2x3V2lkdGgxODQyXGNscGFkZmIzXGNscGFkYjQ1XGNscGFkZmwzXGNscGFkbDQ1XGNscGFkZnIzXGNscGFkcjQ1XGNscGFkZnQzXGNscGFkdDQ1XGNlbGx4LTM1XGNsdmVydGFsY1xjbGJyZHJ0XGJyZHJub25lXGNsYnJkcmxcYnJkcm5vbmVcY2xicmRyYlxicmRybm9uZVxjbGJyZHJyXGJyZHJub25lXGNsdHhscnRiXGNsZnRzV2lkdGgzXGNsd1dpZHRoMzQ1MVxjbHBhZGZiM1xjbHBhZGI0NVxjbHBhZGZsM1xjbHBhZGw0NVxjbHBhZGZyM1xjbHBhZHI0NVxjbHBhZGZ0M1xjbHBhZHQ0NVxjZWxseC0yNVxjbHZlcnRhbGNcY2xicmRydFxicmRybm9uZVxjbGJyZHJsXGJyZHJub25lXGNsYnJkcmJcYnJkcm5vbmVcY2xicmRyclxicmRybm9uZVxjbHR4bHJ0YlxjbGZ0c1dpZHRoM1xjbHdXaWR0aDE1MzZcY2xwYWRmYjNcY2xwYWRiNDVcY2xwYWRmbDNcY2xwYWRsNDVcY2xwYWRmcjNcY2xwYWRyNDVcY2xwYWRmdDNcY2xwYWR0NDVcY2VsbHgtMTVcY2x2ZXJ0YWxjXGNsYnJkcnRcYnJkcm5vbmVcY2xicmRybFxicmRybm9uZVxjbGJyZHJiXGJyZHJub25lXGNsYnJkcnJcYnJkcm5vbmVcY2x0eGxydGJcY2xmdHNXaWR0aDNcY2x3V2lkdGgyODAzXGNscGFkZmIzXGNscGFkYjQ1XGNscGFkZmwzXGNscGFkbDQ1XGNscGFkZnIzXGNscGFkcjQ1XGNscGFkZnQzXGNscGFkdDQ1XGNlbGx4LTVccGFyZFxwbGFpblxxbFxpbnRibHtcYlxmMVxmczIyXGNmMCBBR0UvIEdFTkRFUiB9XGYxXGZzMjJcY2YwXGNlbGxccGFyZFxwbGFpblxxbFxpbnRibHtcZjFcZnMyMlxjZjAgOiBce0FHRVx9IC8gXHtHRU5ERVJcfX1cZjFcZnMyMlxjZjBcY2VsbFxwYXJkXHBsYWluXHFsXGludGJse1xiXGYxXGZzMjJcY2YwIFJFRy4gREFURX1cZjFcZnMyMlxjZjBcY2VsbFxwYXJkXHBsYWluXHFsXGludGJse1xmMVxmczIyXGNmMCA6IFx7UkVHREFURVx9fVxmMVxmczIyXGNmMFxjZWxsXHRyb3dkXGlyb3cxXGlyb3diYW5kMVx0cmxlZnQtNDVcdHJmdHNXaWR0aDNcdHJ3V2lkdGg5NjMyXHRibGluZHR5cGUzXHRibGluZDBcY2x2ZXJ0YWxjXGNsYnJkcnRcYnJkcm5vbmVcY2xicmRybFxicmRybm9uZVxjbGJyZHJiXGJyZHJub25lXGNsYnJkcnJcYnJkcm5vbmVcY2x0eGxydGJcY2xmdHNXaWR0aDNcY2x3V2lkdGgxODQyXGNscGFkZmIzXGNscGFkYjQ1XGNscGFkZmwzXGNscGFkbDQ1XGNscGFkZnIzXGNscGFkcjQ1XGNscGFkZnQzXGNscGFkdDQ1XGNlbGx4LTM1XGNsdmVydGFsY1xjbGJyZHJ0XGJyZHJub25lXGNsYnJkcmxcYnJkcm5vbmVcY2xicmRyYlxicmRybm9uZVxjbGJyZHJyXGJyZHJub25lXGNsdHhscnRiXGNsZnRzV2lkdGgzXGNsd1dpZHRoMzQ1MVxjbHBhZGZiM1xjbHBhZGI0NVxjbHBhZGZsM1xjbHBhZGw0NVxjbHBhZGZyM1xjbHBhZHI0NVxjbHBhZGZ0M1xjbHBhZHQ0NVxjZWxseC0yNVxjbHZlcnRhbGNcY2xicmRydFxicmRybm9uZVxjbGJyZHJsXGJyZHJub25lXGNsYnJkcmJcYnJkcm5vbmVcY2xicmRyclxicmRybm9uZVxjbHR4bHJ0YlxjbGZ0c1dpZHRoM1xjbHdXaWR0aDE1MzZcY2xwYWRmYjNcY2xwYWRiNDVcY2xwYWRmbDNcY2xwYWRsNDVcY2xwYWRmcjNcY2xwYWRyNDVcY2xwYWRmdDNcY2xwYWR0NDVcY2VsbHgtMTVcY2x2ZXJ0YWxjXGNsYnJkcnRcYnJkcm5vbmVcY2xicmRybFxicmRybm9uZVxjbGJyZHJiXGJyZHJub25lXGNsYnJkcnJcYnJkcm5vbmVcY2x0eGxydGJcY2xmdHNXaWR0aDNcY2x3V2lkdGgyODAzXGNscGFkZmIzXGNscGFkYjQ1XGNscGFkZmwzXGNscGFkbDQ1XGNscGFkZnIzXGNscGFkcjQ1XGNscGFkZnQzXGNscGFkdDQ1XGNlbGx4LTVccm93XHRyb3dkXGlyb3cyXGlyb3diYW5kMlxsYXN0cm93XHRybGVmdC00NVx0cmZ0c1dpZHRoM1x0cndXaWR0aDk2MzJcdGJsaW5kdHlwZTNcdGJsaW5kMFxjbHZlcnRhbGNcY2xicmRydFxicmRybm9uZVxjbGJyZHJsXGJyZHJub25lXGNsYnJkcmJcYnJkcm5vbmVcY2xicmRyclxicmRybm9uZVxjbHR4bHJ0YlxjbGZ0c1dpZHRoM1xjbHdXaWR0aDE4NDJcY2xwYWRmYjNcY2xwYWRiNDVcY2xwYWRmbDNcY2xwYWRsNDVcY2xwYWRmcjNcY2xwYWRyNDVcY2xwYWRmdDNcY2xwYWR0NDVcY2VsbHgtMzVcY2x2ZXJ0YWxjXGNsYnJkcnRcYnJkcm5vbmVcY2xicmRybFxicmRybm9uZVxjbGJyZHJiXGJyZHJub25lXGNsYnJkcnJcYnJkcm5vbmVcY2x0eGxydGJcY2xmdHNXaWR0aDNcY2x3V2lkdGgzNDUxXGNscGFkZmIzXGNscGFkYjQ1XGNscGFkZmwzXGNscGFkbDQ1XGNscGFkZnIzXGNscGFkcjQ1XGNscGFkZnQzXGNscGFkdDQ1XGNlbGx4LTI1XGNsdmVydGFsY1xjbGJyZHJ0XGJyZHJub25lXGNsYnJkcmxcYnJkcm5vbmVcY2xicmRyYlxicmRybm9uZVxjbGJyZHJyXGJyZHJub25lXGNsdHhscnRiXGNsZnRzV2lkdGgzXGNsd1dpZHRoMTUzNlxjbHBhZGZiM1xjbHBhZGI0NVxjbHBhZGZsM1xjbHBhZGw0NVxjbHBhZGZyM1xjbHBhZHI0NVxjbHBhZGZ0M1xjbHBhZHQ0NVxjZWxseC0xNVxjbHZlcnRhbGNcY2xicmRydFxicmRybm9uZVxjbGJyZHJsXGJyZHJub25lXGNsYnJkcmJcYnJkcm5vbmVcY2xicmRyclxicmRybm9uZVxjbHR4bHJ0YlxjbGZ0c1dpZHRoM1xjbHdXaWR0aDI4MDNcY2xwYWRmYjNcY2xwYWRiNDVcY2xwYWRmbDNcY2xwYWRsNDVcY2xwYWRmcjNcY2xwYWRyNDVcY2xwYWRmdDNcY2xwYWR0NDVcY2VsbHgtNVxwYXJkXHBsYWluXHFsXGludGJse1xiXGYxXGZzMjJcY2YwIFJFRkVSUkVEIEJZfVxmMVxmczIyXGNmMFxjZWxsXHBhcmRccGxhaW5ccWxcaW50Ymx7XGYxXGZzMjJcY2YwIDogXHtSRUZFUlJBTERPQ1RPUlx9fVxmMVxmczIyXGNmMFxjZWxsXHBhcmRccGxhaW5ccWxcaW50Ymx7XGJcZjFcZnMyMlxjZjAgUkVQLiBEQVRFfVxmMVxmczIyXGNmMFxjZWxsXHBhcmRccGxhaW5ccWxcaW50Ymx7XGYxXGZzMjJcY2YwIDogXHtSRVBPUlRQUklOVEVEVElNRVx9fVxmMVxmczIyXGNmMFxjZWxsXHRyb3dkXGlyb3cyXGlyb3diYW5kMlxsYXN0cm93XHRybGVmdC00NVx0cmZ0c1dpZHRoM1x0cndXaWR0aDk2MzJcdGJsaW5kdHlwZTNcdGJsaW5kMFxjbHZlcnRhbGNcY2xicmRydFxicmRybm9uZVxjbGJyZHJsXGJyZHJub25lXGNsYnJkcmJcYnJkcm5vbmVcY2xicmRyclxicmRybm9uZVxjbHR4bHJ0YlxjbGZ0c1dpZHRoM1xjbHdXaWR0aDE4NDJcY2xwYWRmYjNcY2xwYWRiNDVcY2xwYWRmbDNcY2xwYWRsNDVcY2xwYWRmcjNcY2xwYWRyNDVcY2xwYWRmdDNcY2xwYWR0NDVcY2VsbHgtMzVcY2x2ZXJ0YWxjXGNsYnJkcnRcYnJkcm5vbmVcY2xicmRybFxicmRybm9uZVxjbGJyZHJiXGJyZHJub25lXGNsYnJkcnJcYnJkcm5vbmVcY2x0eGxydGJcY2xmdHNXaWR0aDNcY2x3V2lkdGgzNDUxXGNscGFkZmIzXGNscGFkYjQ1XGNscGFkZmwzXGNscGFkbDQ1XGNscGFkZnIzXGNscGFkcjQ1XGNscGFkZnQzXGNscGFkdDQ1XGNlbGx4LTI1XGNsdmVydGFsY1xjbGJyZHJ0XGJyZHJub25lXGNsYnJkcmxcYnJkcm5vbmVcY2xicmRyYlxicmRybm9uZVxjbGJyZHJyXGJyZHJub25lXGNsdHhscnRiXGNsZnRzV2lkdGgzXGNsd1dpZHRoMTUzNlxjbHBhZGZiM1xjbHBhZGI0NVxjbHBhZGZsM1xjbHBhZGw0NVxjbHBhZGZyM1xjbHBhZHI0NVxjbHBhZGZ0M1xjbHBhZHQ0NVxjZWxseC0xNVxjbHZlcnRhbGNcY2xicmRydFxicmRybm9uZVxjbGJyZHJsXGJyZHJub25lXGNsYnJkcmJcYnJkcm5vbmVcY2xicmRyclxicmRybm9uZVxjbHR4bHJ0YlxjbGZ0c1dpZHRoM1xjbHdXaWR0aDI4MDNcY2xwYWRmYjNcY2xwYWRiNDVcY2xwYWRmbDNcY2xwYWRsNDVcY2xwYWRmcjNcY2xwYWRyNDVcY2xwYWRmdDNcY2xwYWR0NDVcY2VsbHgtNVxyb3dccGFyZFxwbGFpblxxbFxmMVxmczIyXGNmMFxwYXJ9XHBhcmRccGxhaW5ccWxcZnMyMlxjZjBccGFyfQ== 

//   `


// rtf file 
  @Input() blankDocumentWithHeader = `
e1xydGYxXGRlZmYwe1xmb250dGJse1xmMCBDYWxpYnJpO317XGYxIEFyaWFsO319e1xjb2xvcnRibCA7XHJlZDBcZ3JlZW4wXGJsdWUyNTUgO317XCpcZGVmY2hwIFxmczIyfXtcc3R5bGVzaGVldCB7XHFsXGZzMjIgTm9ybWFsO317XCpcY3MxXGZzMjIgRGVmYXVsdCBQYXJhZ3JhcGggRm9udDt9e1wqXGNzMlx1bFxmczIyXGNmMSBIeXBlcmxpbms7fXtcKlx0czNcdHNyb3dkXGZzMjJccWxcdHN2ZXJ0YWx0XGNsdHhscnRiIE5vcm1hbCBUYWJsZTt9fXtcKlxsaXN0b3ZlcnJpZGV0YWJsZX17XGluZm99XG5vdWljb21wYXRcc3BseXR3bmluZVxodG1hdXRzcFxleHBzaHJ0blxzcGx0cGdwYXJcZGVmdGFiNzIwXHNlY3RkXG1hcmdsc3huMTQ0MFxtYXJncnN4bjE0NDBcbWFyZ3RzeG4xNDQwXG1hcmdic3huMTQ0MFxoZWFkZXJ5NzIwXGZvb3Rlcnk3MjBccGd3c3huMTIyNDBccGdoc3huMTU4NDBcY29sczFcY29sc3g3MjB7XGhlYWRlcnJcdHJvd2RcaXJvdzBcaXJvd2JhbmQwXHRybGVmdC00NVx0cmZ0c1dpZHRoM1x0cndXaWR0aDk2MzJcdGJsaW5kdHlwZTNcdGJsaW5kMFxjbHZlcnRhbGNcY2xicmRydFxicmRybm9uZVxjbGJyZHJsXGJyZHJub25lXGNsYnJkcmJcYnJkcm5vbmVcY2xicmRyclxicmRybm9uZVxjbHR4bHJ0YlxjbGZ0c1dpZHRoM1xjbHdXaWR0aDE4NDJcY2xwYWRmYjNcY2xwYWRiNDVcY2xwYWRmbDNcY2xwYWRsNDVcY2xwYWRmcjNcY2xwYWRyNDVcY2xwYWRmdDNcY2xwYWR0NDVcY2VsbHgtMzVcY2x2ZXJ0YWxjXGNsYnJkcnRcYnJkcm5vbmVcY2xicmRybFxicmRybm9uZVxjbGJyZHJiXGJyZHJub25lXGNsYnJkcnJcYnJkcm5vbmVcY2x0eGxydGJcY2xmdHNXaWR0aDNcY2x3V2lkdGgzNDUxXGNscGFkZmIzXGNscGFkYjQ1XGNscGFkZmwzXGNscGFkbDQ1XGNscGFkZnIzXGNscGFkcjQ1XGNscGFkZnQzXGNscGFkdDQ1XGNlbGx4LTI1XGNsdmVydGFsY1xjbGJyZHJ0XGJyZHJub25lXGNsYnJkcmxcYnJkcm5vbmVcY2xicmRyYlxicmRybm9uZVxjbGJyZHJyXGJyZHJub25lXGNsdHhscnRiXGNsZnRzV2lkdGgzXGNsd1dpZHRoMTUzNlxjbHBhZGZiM1xjbHBhZGI0NVxjbHBhZGZsM1xjbHBhZGw0NVxjbHBhZGZyM1xjbHBhZHI0NVxjbHBhZGZ0M1xjbHBhZHQ0NVxjZWxseC0xNVxjbHZlcnRhbGNcY2xicmRydFxicmRybm9uZVxjbGJyZHJsXGJyZHJub25lXGNsYnJkcmJcYnJkcm5vbmVcY2xicmRyclxicmRybm9uZVxjbHR4bHJ0YlxjbGZ0c1dpZHRoM1xjbHdXaWR0aDI4MDNcY2xwYWRmYjNcY2xwYWRiNDVcY2xwYWRmbDNcY2xwYWRsNDVcY2xwYWRmcjNcY2xwYWRyNDVcY2xwYWRmdDNcY2xwYWR0NDVcY2VsbHgtNVxwYXJkXHBsYWluXHFsXGludGJse1xiXGYxXGZzMjJcY2YwIE5BTUV9XGYxXGZzMjJcY2YwXGNlbGxccGFyZFxwbGFpblxxbFxpbnRibHtcZjFcZnMyMlxjZjAgOiBce1RJVExFXH0gXHtQQVRJRU5UTkFNRVx9fVxmMVxmczIyXGNmMFxjZWxsXHBhcmRccGxhaW5ccWxcaW50Ymx7XGJcZjFcZnMyMlxjZjAgUkVHTk99XGYxXGZzMjJcY2YwXGNlbGxccGFyZFxwbGFpblxxbFxpbnRibHtcZjFcZnMyMlxjZjAgOiBce1ZJU0lUSURcfX1cZjFcZnMyMlxjZjBcY2VsbFx0cm93ZFxpcm93MFxpcm93YmFuZDBcdHJsZWZ0LTQ1XHRyZnRzV2lkdGgzXHRyd1dpZHRoOTYzMlx0YmxpbmR0eXBlM1x0YmxpbmQwXGNsdmVydGFsY1xjbGJyZHJ0XGJyZHJub25lXGNsYnJkcmxcYnJkcm5vbmVcY2xicmRyYlxicmRybm9uZVxjbGJyZHJyXGJyZHJub25lXGNsdHhscnRiXGNsZnRzV2lkdGgzXGNsd1dpZHRoMTg0MlxjbHBhZGZiM1xjbHBhZGI0NVxjbHBhZGZsM1xjbHBhZGw0NVxjbHBhZGZyM1xjbHBhZHI0NVxjbHBhZGZ0M1xjbHBhZHQ0NVxjZWxseC0zNVxjbHZlcnRhbGNcY2xicmRydFxicmRybm9uZVxjbGJyZHJsXGJyZHJub25lXGNsYnJkcmJcYnJkcm5vbmVcY2xicmRyclxicmRybm9uZVxjbHR4bHJ0YlxjbGZ0c1dpZHRoM1xjbHdXaWR0aDM0NTFcY2xwYWRmYjNcY2xwYWRiNDVcY2xwYWRmbDNcY2xwYWRsNDVcY2xwYWRmcjNcY2xwYWRyNDVcY2xwYWRmdDNcY2xwYWR0NDVcY2VsbHgtMjVcY2x2ZXJ0YWxjXGNsYnJkcnRcYnJkcm5vbmVcY2xicmRybFxicmRybm9uZVxjbGJyZHJiXGJyZHJub25lXGNsYnJkcnJcYnJkcm5vbmVcY2x0eGxydGJcY2xmdHNXaWR0aDNcY2x3V2lkdGgxNTM2XGNscGFkZmIzXGNscGFkYjQ1XGNscGFkZmwzXGNscGFkbDQ1XGNscGFkZnIzXGNscGFkcjQ1XGNscGFkZnQzXGNscGFkdDQ1XGNlbGx4LTE1XGNsdmVydGFsY1xjbGJyZHJ0XGJyZHJub25lXGNsYnJkcmxcYnJkcm5vbmVcY2xicmRyYlxicmRybm9uZVxjbGJyZHJyXGJyZHJub25lXGNsdHhscnRiXGNsZnRzV2lkdGgzXGNsd1dpZHRoMjgwM1xjbHBhZGZiM1xjbHBhZGI0NVxjbHBhZGZsM1xjbHBhZGw0NVxjbHBhZGZyM1xjbHBhZHI0NVxjbHBhZGZ0M1xjbHBhZHQ0NVxjZWxseC01XHJvd1x0cm93ZFxpcm93MVxpcm93YmFuZDFcdHJsZWZ0LTQ1XHRyZnRzV2lkdGgzXHRyd1dpZHRoOTYzMlx0YmxpbmR0eXBlM1x0YmxpbmQwXGNsdmVydGFsY1xjbGJyZHJ0XGJyZHJub25lXGNsYnJkcmxcYnJkcm5vbmVcY2xicmRyYlxicmRybm9uZVxjbGJyZHJyXGJyZHJub25lXGNsdHhscnRiXGNsZnRzV2lkdGgzXGNsd1dpZHRoMTg0MlxjbHBhZGZiM1xjbHBhZGI0NVxjbHBhZGZsM1xjbHBhZGw0NVxjbHBhZGZyM1xjbHBhZHI0NVxjbHBhZGZ0M1xjbHBhZHQ0NVxjZWxseC0zNVxjbHZlcnRhbGNcY2xicmRydFxicmRybm9uZVxjbGJyZHJsXGJyZHJub25lXGNsYnJkcmJcYnJkcm5vbmVcY2xicmRyclxicmRybm9uZVxjbHR4bHJ0YlxjbGZ0c1dpZHRoM1xjbHdXaWR0aDM0NTFcY2xwYWRmYjNcY2xwYWRiNDVcY2xwYWRmbDNcY2xwYWRsNDVcY2xwYWRmcjNcY2xwYWRyNDVcY2xwYWRmdDNcY2xwYWR0NDVcY2VsbHgtMjVcY2x2ZXJ0YWxjXGNsYnJkcnRcYnJkcm5vbmVcY2xicmRybFxicmRybm9uZVxjbGJyZHJiXGJyZHJub25lXGNsYnJkcnJcYnJkcm5vbmVcY2x0eGxydGJcY2xmdHNXaWR0aDNcY2x3V2lkdGgxNTM2XGNscGFkZmIzXGNscGFkYjQ1XGNscGFkZmwzXGNscGFkbDQ1XGNscGFkZnIzXGNscGFkcjQ1XGNscGFkZnQzXGNscGFkdDQ1XGNlbGx4LTE1XGNsdmVydGFsY1xjbGJyZHJ0XGJyZHJub25lXGNsYnJkcmxcYnJkcm5vbmVcY2xicmRyYlxicmRybm9uZVxjbGJyZHJyXGJyZHJub25lXGNsdHhscnRiXGNsZnRzV2lkdGgzXGNsd1dpZHRoMjgwM1xjbHBhZGZiM1xjbHBhZGI0NVxjbHBhZGZsM1xjbHBhZGw0NVxjbHBhZGZyM1xjbHBhZHI0NVxjbHBhZGZ0M1xjbHBhZHQ0NVxjZWxseC01XHBhcmRccGxhaW5ccWxcaW50Ymx7XGJcZjFcZnMyMlxjZjAgQUdFLyBHRU5ERVIgfVxmMVxmczIyXGNmMFxjZWxsXHBhcmRccGxhaW5ccWxcaW50Ymx7XGYxXGZzMjJcY2YwIDogXHtBR0VcfSAvIFx7R0VOREVSXH19XGYxXGZzMjJcY2YwXGNlbGxccGFyZFxwbGFpblxxbFxpbnRibHtcYlxmMVxmczIyXGNmMCBSRUcuIERBVEV9XGYxXGZzMjJcY2YwXGNlbGxccGFyZFxwbGFpblxxbFxpbnRibHtcZjFcZnMyMlxjZjAgOiBce1JFR0RBVEVcfX1cZjFcZnMyMlxjZjBcY2VsbFx0cm93ZFxpcm93MVxpcm93YmFuZDFcdHJsZWZ0LTQ1XHRyZnRzV2lkdGgzXHRyd1dpZHRoOTYzMlx0YmxpbmR0eXBlM1x0YmxpbmQwXGNsdmVydGFsY1xjbGJyZHJ0XGJyZHJub25lXGNsYnJkcmxcYnJkcm5vbmVcY2xicmRyYlxicmRybm9uZVxjbGJyZHJyXGJyZHJub25lXGNsdHhscnRiXGNsZnRzV2lkdGgzXGNsd1dpZHRoMTg0MlxjbHBhZGZiM1xjbHBhZGI0NVxjbHBhZGZsM1xjbHBhZGw0NVxjbHBhZGZyM1xjbHBhZHI0NVxjbHBhZGZ0M1xjbHBhZHQ0NVxjZWxseC0zNVxjbHZlcnRhbGNcY2xicmRydFxicmRybm9uZVxjbGJyZHJsXGJyZHJub25lXGNsYnJkcmJcYnJkcm5vbmVcY2xicmRyclxicmRybm9uZVxjbHR4bHJ0YlxjbGZ0c1dpZHRoM1xjbHdXaWR0aDM0NTFcY2xwYWRmYjNcY2xwYWRiNDVcY2xwYWRmbDNcY2xwYWRsNDVcY2xwYWRmcjNcY2xwYWRyNDVcY2xwYWRmdDNcY2xwYWR0NDVcY2VsbHgtMjVcY2x2ZXJ0YWxjXGNsYnJkcnRcYnJkcm5vbmVcY2xicmRybFxicmRybm9uZVxjbGJyZHJiXGJyZHJub25lXGNsYnJkcnJcYnJkcm5vbmVcY2x0eGxydGJcY2xmdHNXaWR0aDNcY2x3V2lkdGgxNTM2XGNscGFkZmIzXGNscGFkYjQ1XGNscGFkZmwzXGNscGFkbDQ1XGNscGFkZnIzXGNscGFkcjQ1XGNscGFkZnQzXGNscGFkdDQ1XGNlbGx4LTE1XGNsdmVydGFsY1xjbGJyZHJ0XGJyZHJub25lXGNsYnJkcmxcYnJkcm5vbmVcY2xicmRyYlxicmRybm9uZVxjbGJyZHJyXGJyZHJub25lXGNsdHhscnRiXGNsZnRzV2lkdGgzXGNsd1dpZHRoMjgwM1xjbHBhZGZiM1xjbHBhZGI0NVxjbHBhZGZsM1xjbHBhZGw0NVxjbHBhZGZyM1xjbHBhZHI0NVxjbHBhZGZ0M1xjbHBhZHQ0NVxjZWxseC01XHJvd1x0cm93ZFxpcm93Mlxpcm93YmFuZDJcbGFzdHJvd1x0cmxlZnQtNDVcdHJmdHNXaWR0aDNcdHJ3V2lkdGg5NjMyXHRibGluZHR5cGUzXHRibGluZDBcY2x2ZXJ0YWxjXGNsYnJkcnRcYnJkcm5vbmVcY2xicmRybFxicmRybm9uZVxjbGJyZHJiXGJyZHJub25lXGNsYnJkcnJcYnJkcm5vbmVcY2x0eGxydGJcY2xmdHNXaWR0aDNcY2x3V2lkdGgxODQyXGNscGFkZmIzXGNscGFkYjQ1XGNscGFkZmwzXGNscGFkbDQ1XGNscGFkZnIzXGNscGFkcjQ1XGNscGFkZnQzXGNscGFkdDQ1XGNlbGx4LTM1XGNsdmVydGFsY1xjbGJyZHJ0XGJyZHJub25lXGNsYnJkcmxcYnJkcm5vbmVcY2xicmRyYlxicmRybm9uZVxjbGJyZHJyXGJyZHJub25lXGNsdHhscnRiXGNsZnRzV2lkdGgzXGNsd1dpZHRoMzQ1MVxjbHBhZGZiM1xjbHBhZGI0NVxjbHBhZGZsM1xjbHBhZGw0NVxjbHBhZGZyM1xjbHBhZHI0NVxjbHBhZGZ0M1xjbHBhZHQ0NVxjZWxseC0yNVxjbHZlcnRhbGNcY2xicmRydFxicmRybm9uZVxjbGJyZHJsXGJyZHJub25lXGNsYnJkcmJcYnJkcm5vbmVcY2xicmRyclxicmRybm9uZVxjbHR4bHJ0YlxjbGZ0c1dpZHRoM1xjbHdXaWR0aDE1MzZcY2xwYWRmYjNcY2xwYWRiNDVcY2xwYWRmbDNcY2xwYWRsNDVcY2xwYWRmcjNcY2xwYWRyNDVcY2xwYWRmdDNcY2xwYWR0NDVcY2VsbHgtMTVcY2x2ZXJ0YWxjXGNsYnJkcnRcYnJkcm5vbmVcY2xicmRybFxicmRybm9uZVxjbGJyZHJiXGJyZHJub25lXGNsYnJkcnJcYnJkcm5vbmVcY2x0eGxydGJcY2xmdHNXaWR0aDNcY2x3V2lkdGgyODAzXGNscGFkZmIzXGNscGFkYjQ1XGNscGFkZmwzXGNscGFkbDQ1XGNscGFkZnIzXGNscGFkcjQ1XGNscGFkZnQzXGNscGFkdDQ1XGNlbGx4LTVccGFyZFxwbGFpblxxbFxpbnRibHtcYlxmMVxmczIyXGNmMCBSRUZFUlJFRCBCWX1cZjFcZnMyMlxjZjBcY2VsbFxwYXJkXHBsYWluXHFsXGludGJse1xmMVxmczIyXGNmMCA6IFx7UkVGRVJSQUxET0NUT1JcfX1cZjFcZnMyMlxjZjBcY2VsbFxwYXJkXHBsYWluXHFsXGludGJse1xiXGYxXGZzMjJcY2YwIFJFUC4gREFURX1cZjFcZnMyMlxjZjBcY2VsbFxwYXJkXHBsYWluXHFsXGludGJse1xmMVxmczIyXGNmMCA6IFx7UkVQT1JUUFJJTlRFRFRJTUVcfX1cZjFcZnMyMlxjZjBcY2VsbFx0cm93ZFxpcm93Mlxpcm93YmFuZDJcbGFzdHJvd1x0cmxlZnQtNDVcdHJmdHNXaWR0aDNcdHJ3V2lkdGg5NjMyXHRibGluZHR5cGUzXHRibGluZDBcY2x2ZXJ0YWxjXGNsYnJkcnRcYnJkcm5vbmVcY2xicmRybFxicmRybm9uZVxjbGJyZHJiXGJyZHJub25lXGNsYnJkcnJcYnJkcm5vbmVcY2x0eGxydGJcY2xmdHNXaWR0aDNcY2x3V2lkdGgxODQyXGNscGFkZmIzXGNscGFkYjQ1XGNscGFkZmwzXGNscGFkbDQ1XGNscGFkZnIzXGNscGFkcjQ1XGNscGFkZnQzXGNscGFkdDQ1XGNlbGx4LTM1XGNsdmVydGFsY1xjbGJyZHJ0XGJyZHJub25lXGNsYnJkcmxcYnJkcm5vbmVcY2xicmRyYlxicmRybm9uZVxjbGJyZHJyXGJyZHJub25lXGNsdHhscnRiXGNsZnRzV2lkdGgzXGNsd1dpZHRoMzQ1MVxjbHBhZGZiM1xjbHBhZGI0NVxjbHBhZGZsM1xjbHBhZGw0NVxjbHBhZGZyM1xjbHBhZHI0NVxjbHBhZGZ0M1xjbHBhZHQ0NVxjZWxseC0yNVxjbHZlcnRhbGNcY2xicmRydFxicmRybm9uZVxjbGJyZHJsXGJyZHJub25lXGNsYnJkcmJcYnJkcm5vbmVcY2xicmRyclxicmRybm9uZVxjbHR4bHJ0YlxjbGZ0c1dpZHRoM1xjbHdXaWR0aDE1MzZcY2xwYWRmYjNcY2xwYWRiNDVcY2xwYWRmbDNcY2xwYWRsNDVcY2xwYWRmcjNcY2xwYWRyNDVcY2xwYWRmdDNcY2xwYWR0NDVcY2VsbHgtMTVcY2x2ZXJ0YWxjXGNsYnJkcnRcYnJkcm5vbmVcY2xicmRybFxicmRybm9uZVxjbGJyZHJiXGJyZHJub25lXGNsYnJkcnJcYnJkcm5vbmVcY2x0eGxydGJcY2xmdHNXaWR0aDNcY2x3V2lkdGgyODAzXGNscGFkZmIzXGNscGFkYjQ1XGNscGFkZmwzXGNscGFkbDQ1XGNscGFkZnIzXGNscGFkcjQ1XGNscGFkZnQzXGNscGFkdDQ1XGNlbGx4LTVccm93XHBhcmRccGxhaW5ccWxcZjFcZnMyMlxjZjBccGFyfVxwYXJkXHBsYWluXHFsXGZzMjJcY2YwXHBhcn0= 


  
  `


// docx file 
  // blankDocumentWithHeader = `
  // UEsDBAoAAAAAAMZbJFkAAAAAAAAAAAAAAAAJAAAAZG9jUHJvcHMvUEsDBAoAAAAIAMZbJFkE0gfZRAEAAHMCAAARAAAAZG9jUHJvcHMvY29yZS54bWydks1OwzAQhO88ReR7Yqet+LHSVALEiUpIVAJxM/a2NY0dy9427dvjOm0AqSdu2czs59m1q9neNNkOfNCtnZKyYCQDK1ul7WpKtrjMb8msvqqk47L18OJbBx41hCz22cClm5I1ouOUBrkGI0IRHTaKy9YbgbH0K+qE3IgV0BFj19QACiVQ0CMwdwORnJBKDki39U0CKEmhAQMWAy2Lkv54EbwJFxuS8stpNB4cXLQq2YuDex/0YOy6rujGKUbMX9L3+fNrGjXXNqCwEkhdKclRYwM0fYbt5xdI7AvpQWDrYxGXuIFD13oVeklBkF47jLvv5UYEnMflLzWo+0P/z8NOH2+nLisaCUMZz0wj8nQAqCyG5v2IZ+Vt/PC4eCL1iI0mObvL2WRR3nDGeDn+qOjZdeo/Ju+B5pTg38QzoE6J/z6c+htQSwMECgAAAAAAxlskWQAAAAAAAAAAAAAAAAUAAAB3b3JkL1BLAwQKAAAACADGWyRZgUGu18oBAACdBAAAEQAAAHdvcmQvZG9jdW1lbnQueG1snZRNj5swEIbv/RXI9wSI9qNFS/awK1U9VFq1h54dM4BV2+OOTdj8+w4QEjWk1W4v4JFnHt53GPvh8dWaZA8UNLpS5OtMJOAUVto1pehivfooHrcfHvqiQtVZcDHhAheKvhRtjL5I06BasDKs0YPjvRrJysghNWmPVHlCBSEwz5p0k2V3qZXaiRnjwwJktSIMWMe1QptiXWsFI4rL8+wC+r2VHmaaVQvYFVVW0s/OrxjuZdQ7bXQ8jMpmTJ9n7J1ccbS2OikaiopJUTGYmyv2/8rfWzPn9Z67etG3E/wtdj8Tdv5MW/p9F+1Jur0MM44W0q40bzL/fByG6YcSGG4kutBqf6LJt9Aqkv1fJsPrpbkrei4IXBU7Og1E7/9DxZ9T+zxJnJvU+/xmwXxX009Aq4ovjUOSOwOlGMBiywdth9VhePt0eAZQ8YWGVQuyAvoGNRCfUEj6Ih48F1ZQy85EkVChK5Y2puVirB4yOHEvTSkcvMYX2cC045uvknjLQB1LcXd/Kzgg3bTnKCJ3j++DQVKMaEuxybMxnr7B18Wn2zGuESPw+Nxvsomu0ASug1+dND90FVvOHUDBS8WSj3np2R4vJ9+8mG+a7W9QSwMECgAAAAgAxlskWbDznM9CBQAA82IAABAAAAB3b3JkL2hlYWRlcjEueG1s7V3db9s2EH/fX2HoPfFHPpAJtQs3VgMDaWI4woY90jRtc5VIgpKtZMX+9x1FSqksu3HjVtmGe4ltUjwdj+TveB9k3r1/jKPWhumES9H3uqcdr8UElXMuln1vnS5Orrz3g1/eZf5qrlvwrEj8rO+t0lT57XZCVywmyalUTEDdQuqYpPBTL9uZ1HOlJWVJAqTiqN3rdC7bMeHCK8iopEYo5lTLRC7SUyrjtlwsOGU5KWje7WwRfVgRxQpqMa0R28FVTPTntToB4oqkfMYjnj7lnBVksm4Huq2F77p2UnJkGvmWI990rmix+dbzmzgqnssUCHRLbiXxQ7p7o+VaPVOr9/e7qF0TsSFJQU7XWNshPNv5kaTrmInUDqhmEQhSimTFVUmNHEJtrkm2Z2YoXu/cDn62KECrdK3LCZGpV3BRnbUjy2IhpEx1z2s0v0voJcGY+uOlkJrMItb3DGFvAGssnUXuY6Ldl4f0KWKtzN+QqO+FHa/tysdiDqWwFGHBQsMnBXTmj6SsvyVPcp2WVQv+yOZl5e+26a+XZ71a63bORvn+G83n9p2WI5q/n7p66ih1r87rlIAQ/QArBcAlbyQVvDbvh+CR5SViC8NjtXAm01TGtWLNl6vthw2zlXfQT8Tymb8MxHN+Ueth5rvX7qsuGdj3QMHK7vqcKcfHZhjxpSj6QmHdMG26nj9jhaiMcJT9/ictHjUsWhklilBYKFARccGmazNjyDqVpl+mpO/1zt28UJXZMnGl2tLWH6VIE2hEEsp53xtqTgCdANmHIil/52M9g9J8TBwFvvWbEmUIff1IEpMout5Rnmr+uZzAjp6QEy3lYovEhgierLYKqYykLsrybuccJn8VZb2eFdO6KBBSMCe5lVkjOZc0YkSbzub0ngW44BGsq2e6oAnTypDNSMKMlC3FiIilHb1cqDCKbuDySXeEoLuWPgp6t6BhmQ/uhp+CfN3kqwcEbqTvVpIFpZ3QdHZ+0TUDvw2RFdhAaEJosisQocmpZtQBpdr+pg4AZDEGjW/UNOhipVnC9IZ5A79VQavMP1ZHoDJ+aSAGX8JxeFvVEij3n7wJMrr5b5zqXoP7zr2Yg5DTb3gcBl9w6jct8skwHAd3Yc0gQKhvHOoPs8G6F2eXaIM591zu+kH3kHPRoHvoED8cuode3PpPg5u7+4ouPgybeledM8QmxCZ0XUMYAmMEBgp+aIxgr62G/iGIvDRrNKOx1rzIfxs/jMPxqKKZ0VB7W0PNmCA2TG7/YlDf6D6XX4BBfZNUYqPsGNT3Majf935O9sTendHwJmi3boK7UTCtOrQPs+gw4v9VMhh6m0ziXIFn6G06xNuEgeaXvE0Y8S8S694y/Q4UCFp0zVt0oJ7Rmmvac4EZFk07i3ZjfKtd3ZKiK6MBVwbmWDQ9+QfW/EKcf1ucP8zgxfQKNHjx9A066hp31EHOxWlrNAyr9sBhoIV5FwhaCFpHgBZ66dBL5+bAv/qQLHrp3Pn25s4lG5GDbq5pZnRWNOCsqHrqKpshE4zDvIutk9iYd4GXKZgbKsxKcTdVmIP8R+yMMFv+dTujafAxmE6DUevDHxXHXwXDAMJ2p4th2gUadGjQHQFbaNC9DrYwkb75HACMyDUekbPaeXg7ur8O76cVBY123dvadXv3RBiZwz0R7omO2BOhKfe6PdE0mGBkzt5lWdwmuvtcD6hOPPeDl3n+UP8TGnKvAy005NCQy/zk/3xIx0bmJvfTcDId34XBKBxv3WqLttzb2nIuRmc+7G3seD+302f/3fu5ywAG/BOLwT9QSwMECgAAAAgAxlskWX8nzXFVAgAA9wYAAA8AAAB3b3JkL3N0eWxlcy54bWzdVMtu2zAQvPcrBN4bOUZRtEbkwHBRtEBgGG1+YEVREmuKJEjKSvr1Xb4cW0kboIce6ou8o9Xs7nCWN7cPgyiOzFiuZEWurxakYJKqhsuuIqNr334gt+s3N9PKukfBbIHp0q6mivTO6VVZWtqzAeyV0kziu1aZARyGpisnZRptFGXWItsgyuVi8b4cgEuyRsJG0U+shVE460OzNylMUXh8VtLZYlqBpZxXZAuC14YTRPqNtGdI6dNrxI8gKrIgIeazmIL2ZOcpdgAhti/gzvADmyVLtTdKtTP0CJLbfgZSJZTJGIxOxY7sz4wtlxEZMyCVZCmpbzJIBQPjxw18FQlMGLZc4JhPvHiCbiN4J/OHNVgmeGYUIDtUpAwy5+eZ3PpCfIy8mgfG9I49uEyZRPXwHTLPlZx4o6YtnpdRIn9ynQYatTZoA//ZbhxqtFvOSKT2hZHnM9rEskE1vzzqnsk5C8Xq2PAI4rsGiqabVflBMyBY61Jvp0wv17dRsCeVPVKR5TtcCjQXQ3NjGAJoHTPpf3zhu7KR6zxnBkdbSn++LTfWeUVSum8p/TW868P/kK5G5xu5O55k/ehbx8MMBxWfp8PEcLZZYXOxoHvUWEuDgc6A7v1M4dXXpiL7MFUT9xHvgbChEobTBuz8YosoGZYNjeHKxj4CjbfMZSnaYy2KQl2U2r5WKo1S7HOnhb8FYum/LPl8HjQQMyjr4cT7H903C/y1bZzsDzeOv5bFP7xzfmMTBzV2ce7G+9csEt1Y3IcvgxddLZIrXfQI+p3O/ImrEVqw619QSwMECgAAAAgAxlskWfB8RZBgAQAAmAIAABEAAAB3b3JkL3NldHRpbmdzLnhtbGWSQW/CMAyF7/sVKPdR6AabEAVtp12mHZh2N4nbRqRxlKR0/Ps5pRHSuNnfe070nGz3v52ZndEHTbYSy/lCzNBKUto2lehj/fgq9ruH7bAJGCPDMOMBGzZDJdoY3aYogmyxgzAnh5a1mnwHkVvfFAN55TxJDIFHO1OUi8W66EBbseMjlQ7OwOUd5Knx1Ft1aMHhbNicwVRiIYrRhDX0Jn7D8RDJZfGlnGToI31cXIsWIkfI+qTiGe2bVV9KfSAoTvlPl9Q5iOmaa3W4hmSXhQ4rcaX6qI2Ol09SKFjqvb4L32npKVAd5zxSUF1riWP8NDDGWZYpT5FvGqOR/AEfxpjS+ENaJH6Cc7wsHjs2y0oY3bRxmU6J3Cnwp7E5NuWklaPGXdLGBqREm9xTkQzXkl1TcWNPmT3d2HNmzze2ymx1Y+vM1om1F4feaHvi7eQy8ZqMoQEVP1PW79C0m/zJdn9QSwMECgAAAAAAxlskWQAAAAAAAAAAAAAAAAsAAAB3b3JkL3RoZW1lL1BLAwQKAAAACADGWyRZYJny8aUGAADSGwAAFQAAAHdvcmQvdGhlbWUvdGhlbWUxLnhtbO1ZzW8cNRS/81eM5t5mP5Mm6qZqPgtJ2igbinr0znhm3HjGI9ubdG8oPXFBQiqIA5W4cUCISlSi4sIfE6kVlD+CZ3tm1s46JG0CFNFESmbsn9/3e3723Lz1KKfBIeaCsGIQtq+3wgAXEYtJkQ7CsUyu3QhvLX9wEy3JDOc4AHQhltAgzKQsl+bmRATDSFxnJS5gLmE8RxJeeToXc3QEVHI612m15udyRIowKFCOB+G9JCERDpdrsusUaBdSqIGI8qEiiiusRsUHbTUnJmKV8uAQ0UEItGN2tI8fyTCgSEiYGIQt/RPOLd+cQ0vVIirPWGutS/RPta5aEB903oanXkSlWcvTUSMwXsDzeL7hoQEoikBvI5+N7fUWOlGvwlog8+ihHS/E3baDt+h3tR42fdRXvw5egwz93gw+SSKwrIPXIIPvz+D7o8VR7NLXIIOfn8EvtFDcW3Doa1BGSXEwg27157tRrW0DSRi944Uv9nvJQqciPkVBhDSxplgkrJBO5FlRmqOHjG8AQAEpkqQI5KTECYogmlcRJSNOgm2SZhCMJSqYgOFWp7XR6sJf9dvTT9qjaAkja7WSCyQRM0NKnkBEnJRyEN7maBRakH2SYxHcxUfBHstRYYg4K1Zwkdor7nNIGOQBrqJC2MD1cQnpR7zQDHMbuktRIVGKCyyDVZhjBxh7OKzhQ2Qv20FFiqgHuC4zYgPvThD1ybGJmSPHcEIThH1W2Bw/dJEZH0viYb055mOb9R5Chz7cHZDdxr3+7os/nn4a/P7Tt6+ffOmhC3jHuq9++OzVL79WsaJd73gN4BBC09h6+dWzV8+fvfz689++f+KjjkeOeueHxUcQng6DFy9Ojp+fHP988vjxyfGPZwq2leUOpx3G6Arj3tDbUoFmKbE/Bn97pN9GjNm4NXawmqG89GF36CS3sVuIS3LgRTLXQzvwzihBRbCCiNf39/jEkXcLEtov8ZAUmS3Fh+IA7ICCXSZ9ogwnPLLh60KCxVJMWbAeYyF8a/ZRTu0120hmXhymTsBuorFEuS9k9zPkqLdzP1gBg3gcAkgn/24XqUAFUnXGhyYjJ1Z3SMSZYIkM7pAcEheMOhvgH0ORtNWbLlIzY+5Zcp9gh8/5Qf6AEEePKZMHZBoFsAE4dT0nxblF/lR57/9N5f02J94C+b6oq83wHS3qntC9ZDk/Kww8RRy2iJffPPWIcLpwr6FxsYuhjM3m5vu6XXVb//W6vcp4TN61sn1WMF+8WE/rM5Ru1TaZdl0377n9QigdygnF20I37AJ2u3gDBhVSn1hxcyorM3hUuQAkHVzKkV4TcCY/ITIbZqiErr6tz6OpqEinIiiZgGZfD3tpK6ZwYJDm2NpXJ1STewLJHRab4a59cG3IaKlSfSyuGXUVgYsy6y5cjlnbSHWm2VzV2lo0XVYc1RqVlYn10R5M3qgGg401oe0KoD8CK8/DnYGSHQ5AiOJY2d34qHaLYl0/X4mLRIZiXPlI6T3ro7Z2Uh0rM4ooPUww3NCi/6XVLG6LiuwluF3ESTa73hnsau9dxkv1FUHtGe3l5FQ60sJOTloER4Nwsd/ph0GEykGYwPkaHvMSvC5UK49oCldTkeQm7M9NZm34qTcXa8Ug+qyMa7fq8RmFnTpQciHXkMhMaOipKgRooTgZ+Tt9MOtVKeCpRheTonsDguFfkwLs6LoWJwmOpO1sa0TZzrxWpZSNJebDLD4KRnTM9xC4X4Uq6BMTAV2frgjqBe75lLX1lFucq8Jo33RpnBlHtMxQVW5VitaZbOA6VBsZ9JslHujmlV0r9+aq6JS/IlXsMP6fqaL2E7h86sbKAxFcLXMUqEwZhIzLjEEVKjMSbXBoFXTtgGiBu2KYhqCi6r4b/nN8qP6bnDM0dFqry7w9kgacwH4kM47xLpQlHX3nEGtXe5chSStCOqIscUVpxB7hQ0z3VQ2cV3t7GGQQ6rqaVGVA407Hn/teZdAoVU2OnW9OJWv2XpMD/3TnY5IZlHLrsG5oavs3ImpruZ2PWa+X13uvrYiamLZZvTorgJm1FSxWaf+WIrzhVmsq1ozGnX4tHHhxVmMYbBqiEi5/4EJZQkxEhEfUfDNRG+o+24PaGsCHEEUMwgai+pppPAJVIM3gCBonM2iCSZEypq26W2W1erO+kjZq6oKG7yljK8ku4u83NHbTnLnsnFy8SmNXFnZsbcbONDV49nSKwlAyPbrAm/7MZn8PY6OH4Og1+NYwplLoYIJvXhxBDz3UeQDJbzjqpct/AlBLAwQKAAAAAADGWyRZAAAAAAAAAAAAAAAABgAAAF9yZWxzL1BLAwQKAAAACADGWyRZjdpueckAAACqAQAACwAAAF9yZWxzLy5yZWxzlZDLTsQwDEX3fEXl/dSFBUJo0tnMhh0a8QNW4rYRk4ccD4+/xyAQVBokWDq+Pj7xdveSjt0TS4slO7jsB+g4+xJinh2cdNrcwG682B74SGqRtsTaOpvJzcGiWm8Rm184UetL5WydqUgitVJmrOQfaWa8GoZrlJ8MGFfM7i44ONjyh9fKfyGXaYqe98WfEmc9swDXCSOTzKwOnosEDJ+DvQkDnnHxRfg/Pr//FBMrBVLCd+amit1JNHL7VjKbe3tuH4kvJVzdfHwDUEsDBAoAAAAAAMZbJFkAAAAAAAAAAAAAAAALAAAAd29yZC9fcmVscy9QSwMECgAAAAgAxlskWW8F5aLVAAAApgIAABwAAAB3b3JkL19yZWxzL2RvY3VtZW50LnhtbC5yZWxzrZK7rsIwDIZ3niLKTt0yIHREy8LCCrxAlLoX0SZRbBC8PeYOEkJn6BLpz+XzlzjzxbHv1AEjtd7lOktSrdBZX7auzvWeq/FML4rRfI2dYdlCTRtIyRlHuW6Ywx8A2QZ7Q4kP6GSl8rE3LDHWEIzdmRphkqZTiO8MXXww1aoUHpoSY6bV9hTwP3hfVa3Fpbf7Hh1/qQI3pBBNrJGfJRLx1PBFQe654VOHg0rQhUgviVv+6YDM0gEaVuMOfRO5z/xS2Upzh30OvhBfEtcI1zF7iMDHfyvOUEsDBAoAAAAIAMZbJFnNK50+NgEAAAQEAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbLWTz07DMAzG7zxFlStq03FACLXdAbjCDrxAlLprtOaPYm9sb4/bbjugtdMEXCIltr/vF8cplnvbJTuIaLwrxSLLRQJO+9q4dSm21KRPYlndFZ+HAJhwrsNStEThWUrULViFmQ/gONL4aBXxNq5lUHqj1iAf8vxRau8IHKXUa4iqeIVGbTtK3vZ8PPpG6FAkL2Ni71UKFUJntCLmkjtX/3BJjw4ZVw452JqA94wh5EWHPjJtcKz74EZEU0OyUpHelWUM+eVjLWuvt5bvkM3LXOD0TWM0nOt7tRC9BkTusO2yc8Qq4078kxxIhw7w7ylG3ev2QMTY/wFwVJ5D4Fatog/IAxXh9h6cJqavTvkNAkQycJ6ZyZ63oGqIi9sNrz39KDx342H2iH8ZyGH9PcQgc7KUw6+uvgFQSwECFAAKAAAAAADGWyRZAAAAAAAAAAAAAAAACQAAAAAAAAAAABAAAAAAAAAAZG9jUHJvcHMvUEsBAhQACgAAAAgAxlskWQTSB9lEAQAAcwIAABEAAAAAAAAAAAAAAAAAJwAAAGRvY1Byb3BzL2NvcmUueG1sUEsBAhQACgAAAAAAxlskWQAAAAAAAAAAAAAAAAUAAAAAAAAAAAAQAAAAmgEAAHdvcmQvUEsBAhQACgAAAAgAxlskWYFBrtfKAQAAnQQAABEAAAAAAAAAAAAAAAAAvQEAAHdvcmQvZG9jdW1lbnQueG1sUEsBAhQACgAAAAgAxlskWbDznM9CBQAA82IAABAAAAAAAAAAAAAAAAAAtgMAAHdvcmQvaGVhZGVyMS54bWxQSwECFAAKAAAACADGWyRZfyfNcVUCAAD3BgAADwAAAAAAAAAAAAAAAAAmCQAAd29yZC9zdHlsZXMueG1sUEsBAhQACgAAAAgAxlskWfB8RZBgAQAAmAIAABEAAAAAAAAAAAAAAAAAqAsAAHdvcmQvc2V0dGluZ3MueG1sUEsBAhQACgAAAAAAxlskWQAAAAAAAAAAAAAAAAsAAAAAAAAAAAAQAAAANw0AAHdvcmQvdGhlbWUvUEsBAhQACgAAAAgAxlskWWCZ8vGlBgAA0hsAABUAAAAAAAAAAAAAAAAAYA0AAHdvcmQvdGhlbWUvdGhlbWUxLnhtbFBLAQIUAAoAAAAAAMZbJFkAAAAAAAAAAAAAAAAGAAAAAAAAAAAAEAAAADgUAABfcmVscy9QSwECFAAKAAAACADGWyRZjdpueckAAACqAQAACwAAAAAAAAAAAAAAAABcFAAAX3JlbHMvLnJlbHNQSwECFAAKAAAAAADGWyRZAAAAAAAAAAAAAAAACwAAAAAAAAAAABAAAABOFQAAd29yZC9fcmVscy9QSwECFAAKAAAACADGWyRZbwXlotUAAACmAgAAHAAAAAAAAAAAAAAAAAB3FQAAd29yZC9fcmVscy9kb2N1bWVudC54bWwucmVsc1BLAQIUAAoAAAAIAMZbJFnNK50+NgEAAAQEAAATAAAAAAAAAAAAAAAAAIYWAABbQ29udGVudF9UeXBlc10ueG1sUEsFBgAAAAAOAA4ATwMAAO0XAAAAAA==
  // `









  rtfToBase64(rtfContent: any) {
    return btoa(rtfContent); // Encode RTF string back to Base64
  }

  changeRtf(base64String: any, targetName: any, tagName: any){

    function base64ToRtf(base64: any) {
      return atob(base64); // Decode Base64 to RTF string
    }

    function replacePatientName(rtfContent: any, name: any) {
      // const placeholder = "\\{PATIENTNAME\\}"; // Notice the double backslash
      const placeholder = tagName;

      if (rtfContent.includes(placeholder)) {
          return rtfContent.replace(placeholder, name); // Replace placeholder with actual name
      } else {
          return rtfContent;
      }
    }


    // const base64String = "e1xydGYxXGRlZmYwe1xmb250dGJse1xmMCBDYWxpYnJpO317XGYxIEFyaWFsO319e1xjb2xvcnRibCA7XHJlZDBcZ3JlZW4wXGJsdWUyNTUgO317XCpcZGVmY2hwIFxmczIyfXtcc3R5bGVzaGVldCB7XHFsXGZzMjIgTm9ybWFsO317XCpcY3MxXGZzMjIgRGVmYXVsdCBQYXJhZ3JhcGggRm9udDt9e1wqXGNzMlx1bFxmczIyXGNmMSBIeXBlcmxpbms7fXtcKlx0czNcdHNyb3dkXGZzMjJccWxcdHN2ZXJ0YWx0XGNsdHhscnRiIE5vcm1hbCBUYWJsZTt9fXtcKlxsaXN0b3ZlcnJpZGV0YWJsZX17XGluZm99XG5vdWljb21wYXRcc3BseXR3bmluZVxodG1hdXRzcFxleHBzaHJ0blxzcGx0cGdwYXJcZGVmdGFiNzIwXHNlY3RkXG1hcmdsc3huMTQ0MFxtYXJncnN4bjE0NDBcbWFyZ3RzeG4xNDQwXG1hcmdic3huMTQ0MFxoZWFkZXJ5NzIwXGZvb3Rlcnk3MjBccGd3c3huMTIyNDBccGdoc3huMTU4NDBcY29sczFcY29sc3g3MjB7XGhlYWRlcnJcdHJvd2RcaXJvdzBcaXJvd2JhbmQwXHRybGVmdC00NVx0cmZ0c1dpZHRoM1x0cndXaWR0aDk2MzJcdGJsaW5kdHlwZTNcdGJsaW5kMFxjbHZlcnRhbGNcY2xicmRydFxicmRybm9uZVxjbGJyZHJsXGJyZHJub25lXGNsYnJkcmJcYnJkcm5vbmVcY2xicmRyclxicmRybm9uZVxjbHR4bHJ0YlxjbGZ0c1dpZHRoM1xjbHdXaWR0aDE4NDJcY2xwYWRmYjNcY2xwYWRiNDVcY2xwYWRmbDNcY2xwYWRsNDVcY2xwYWRmcjNcY2xwYWRyNDVcY2xwYWRmdDNcY2xwYWR0NDVcY2VsbHgtMzVcY2x2ZXJ0YWxjXGNsYnJkcnRcYnJkcm5vbmVcY2xicmRybFxicmRybm9uZVxjbGJyZHJiXGJyZHJub25lXGNsYnJkcnJcYnJkcm5vbmVcY2x0eGxydGJcY2xmdHNXaWR0aDNcY2x3V2lkdGgzNDUxXGNscGFkZmIzXGNscGFkYjQ1XGNscGFkZmwzXGNscGFkbDQ1XGNscGFkZnIzXGNscGFkcjQ1XGNscGFkZnQzXGNscGFkdDQ1XGNlbGx4LTI1XGNsdmVydGFsY1xjbGJyZHJ0XGJyZHJub25lXGNsYnJkcmxcYnJkcm5vbmVcY2xicmRyYlxicmRybm9uZVxjbGJyZHJyXGJyZHJub25lXGNsdHhscnRiXGNsZnRzV2lkdGgzXGNsd1dpZHRoMTUzNlxjbHBhZGZiM1xjbHBhZGI0NVxjbHBhZGZsM1xjbHBhZGw0NVxjbHBhZGZyM1xjbHBhZHI0NVxjbHBhZGZ0M1xjbHBhZHQ0NVxjZWxseC0xNVxjbHZlcnRhbGNcY2xicmRydFxicmRybm9uZVxjbGJyZHJsXGJyZHJub25lXGNsYnJkcmJcYnJkcm5vbmVcY2xicmRyclxicmRybm9uZVxjbHR4bHJ0YlxjbGZ0c1dpZHRoM1xjbHdXaWR0aDI4MDNcY2xwYWRmYjNcY2xwYWRiNDVcY2xwYWRmbDNcY2xwYWRsNDVcY2xwYWRmcjNcY2xwYWRyNDVcY2xwYWRmdDNcY2xwYWR0NDVcY2VsbHgtNVxwYXJkXHBsYWluXHFsXGludGJse1xiXGYxXGZzMjJcY2YwIE5BTUV9XGYxXGZzMjJcY2YwXGNlbGxccGFyZFxwbGFpblxxbFxpbnRibHtcZjFcZnMyMlxjZjAgOiBce1RJVExFXH0gXHtQQVRJRU5UTkFNRVx9fVxmMVxmczIyXGNmMFxjZWxsXHBhcmRccGxhaW5ccWxcaW50Ymx7XGJcZjFcZnMyMlxjZjAgUkVHTk99XGYxXGZzMjJcY2YwXGNlbGxccGFyZFxwbGFpblxxbFxpbnRibHtcZjFcZnMyMlxjZjAgOiBce1ZJU0lUSURcfX1cZjFcZnMyMlxjZjBcY2VsbFx0cm93ZFxpcm93MFxpcm93YmFuZDBcdHJsZWZ0LTQ1XHRyZnRzV2lkdGgzXHRyd1dpZHRoOTYzMlx0YmxpbmR0eXBlM1x0YmxpbmQwXGNsdmVydGFsY1xjbGJyZHJ0XGJyZHJub25lXGNsYnJkcmxcYnJkcm5vbmVcY2xicmRyYlxicmRybm9uZVxjbGJyZHJyXGJyZHJub25lXGNsdHhscnRiXGNsZnRzV2lkdGgzXGNsd1dpZHRoMTg0MlxjbHBhZGZiM1xjbHBhZGI0NVxjbHBhZGZsM1xjbHBhZGw0NVxjbHBhZGZyM1xjbHBhZHI0NVxjbHBhZGZ0M1xjbHBhZHQ0NVxjZWxseC0zNVxjbHZlcnRhbGNcY2xicmRydFxicmRybm9uZVxjbGJyZHJsXGJyZHJub25lXGNsYnJkcmJcYnJkcm5vbmVcY2xicmRyclxicmRybm9uZVxjbHR4bHJ0YlxjbGZ0c1dpZHRoM1xjbHdXaWR0aDM0NTFcY2xwYWRmYjNcY2xwYWRiNDVcY2xwYWRmbDNcY2xwYWRsNDVcY2xwYWRmcjNcY2xwYWRyNDVcY2xwYWRmdDNcY2xwYWR0NDVcY2VsbHgtMjVcY2x2ZXJ0YWxjXGNsYnJkcnRcYnJkcm5vbmVcY2xicmRybFxicmRybm9uZVxjbGJyZHJiXGJyZHJub25lXGNsYnJkcnJcYnJkcm5vbmVcY2x0eGxydGJcY2xmdHNXaWR0aDNcY2x3V2lkdGgxNTM2XGNscGFkZmIzXGNscGFkYjQ1XGNscGFkZmwzXGNscGFkbDQ1XGNscGFkZnIzXGNscGFkcjQ1XGNscGFkZnQzXGNscGFkdDQ1XGNlbGx4LTE1XGNsdmVydGFsY1xjbGJyZHJ0XGJyZHJub25lXGNsYnJkcmxcYnJkcm5vbmVcY2xicmRyYlxicmRybm9uZVxjbGJyZHJyXGJyZHJub25lXGNsdHhscnRiXGNsZnRzV2lkdGgzXGNsd1dpZHRoMjgwM1xjbHBhZGZiM1xjbHBhZGI0NVxjbHBhZGZsM1xjbHBhZGw0NVxjbHBhZGZyM1xjbHBhZHI0NVxjbHBhZGZ0M1xjbHBhZHQ0NVxjZWxseC01XHJvd1x0cm93ZFxpcm93MVxpcm93YmFuZDFcdHJsZWZ0LTQ1XHRyZnRzV2lkdGgzXHRyd1dpZHRoOTYzMlx0YmxpbmR0eXBlM1x0YmxpbmQwXGNsdmVydGFsY1xjbGJyZHJ0XGJyZHJub25lXGNsYnJkcmxcYnJkcm5vbmVcY2xicmRyYlxicmRybm9uZVxjbGJyZHJyXGJyZHJub25lXGNsdHhscnRiXGNsZnRzV2lkdGgzXGNsd1dpZHRoMTg0MlxjbHBhZGZiM1xjbHBhZGI0NVxjbHBhZGZsM1xjbHBhZGw0NVxjbHBhZGZyM1xjbHBhZHI0NVxjbHBhZGZ0M1xjbHBhZHQ0NVxjZWxseC0zNVxjbHZlcnRhbGNcY2xicmRydFxicmRybm9uZVxjbGJyZHJsXGJyZHJub25lXGNsYnJkcmJcYnJkcm5vbmVcY2xicmRyclxicmRybm9uZVxjbHR4bHJ0YlxjbGZ0c1dpZHRoM1xjbHdXaWR0aDM0NTFcY2xwYWRmYjNcY2xwYWRiNDVcY2xwYWRmbDNcY2xwYWRsNDVcY2xwYWRmcjNcY2xwYWRyNDVcY2xwYWRmdDNcY2xwYWR0NDVcY2VsbHgtMjVcY2x2ZXJ0YWxjXGNsYnJkcnRcYnJkcm5vbmVcY2xicmRybFxicmRybm9uZVxjbGJyZHJiXGJyZHJub25lXGNsYnJkcnJcYnJkcm5vbmVcY2x0eGxydGJcY2xmdHNXaWR0aDNcY2x3V2lkdGgxNTM2XGNscGFkZmIzXGNscGFkYjQ1XGNscGFkZmwzXGNscGFkbDQ1XGNscGFkZnIzXGNscGFkcjQ1XGNscGFkZnQzXGNscGFkdDQ1XGNlbGx4LTE1XGNsdmVydGFsY1xjbGJyZHJ0XGJyZHJub25lXGNsYnJkcmxcYnJkcm5vbmVcY2xicmRyYlxicmRybm9uZVxjbGJyZHJyXGJyZHJub25lXGNsdHhscnRiXGNsZnRzV2lkdGgzXGNsd1dpZHRoMjgwM1xjbHBhZGZiM1xjbHBhZGI0NVxjbHBhZGZsM1xjbHBhZGw0NVxjbHBhZGZyM1xjbHBhZHI0NVxjbHBhZGZ0M1xjbHBhZHQ0NVxjZWxseC01XHBhcmRccGxhaW5ccWxcaW50Ymx7XGJcZjFcZnMyMlxjZjAgQUdFLyBHRU5ERVIgfVxmMVxmczIyXGNmMFxjZWxsXHBhcmRccGxhaW5ccWxcaW50Ymx7XGYxXGZzMjJcY2YwIDogXHtBR0VcfSAvIFx7R0VOREVSXH19XGYxXGZzMjJcY2YwXGNlbGxccGFyZFxwbGFpblxxbFxpbnRibHtcYlxmMVxmczIyXGNmMCBSRUcuIERBVEV9XGYxXGZzMjJcY2YwXGNlbGxccGFyZFxwbGFpblxxbFxpbnRibHtcZjFcZnMyMlxjZjAgOiBce1JFR0RBVEVcfX1cZjFcZnMyMlxjZjBcY2VsbFx0cm93ZFxpcm93MVxpcm93YmFuZDFcdHJsZWZ0LTQ1XHRyZnRzV2lkdGgzXHRyd1dpZHRoOTYzMlx0YmxpbmR0eXBlM1x0YmxpbmQwXGNsdmVydGFsY1xjbGJyZHJ0XGJyZHJub25lXGNsYnJkcmxcYnJkcm5vbmVcY2xicmRyYlxicmRybm9uZVxjbGJyZHJyXGJyZHJub25lXGNsdHhscnRiXGNsZnRzV2lkdGgzXGNsd1dpZHRoMTg0MlxjbHBhZGZiM1xjbHBhZGI0NVxjbHBhZGZsM1xjbHBhZGw0NVxjbHBhZGZyM1xjbHBhZHI0NVxjbHBhZGZ0M1xjbHBhZHQ0NVxjZWxseC0zNVxjbHZlcnRhbGNcY2xicmRydFxicmRybm9uZVxjbGJyZHJsXGJyZHJub25lXGNsYnJkcmJcYnJkcm5vbmVcY2xicmRyclxicmRybm9uZVxjbHR4bHJ0YlxjbGZ0c1dpZHRoM1xjbHdXaWR0aDM0NTFcY2xwYWRmYjNcY2xwYWRiNDVcY2xwYWRmbDNcY2xwYWRsNDVcY2xwYWRmcjNcY2xwYWRyNDVcY2xwYWRmdDNcY2xwYWR0NDVcY2VsbHgtMjVcY2x2ZXJ0YWxjXGNsYnJkcnRcYnJkcm5vbmVcY2xicmRybFxicmRybm9uZVxjbGJyZHJiXGJyZHJub25lXGNsYnJkcnJcYnJkcm5vbmVcY2x0eGxydGJcY2xmdHNXaWR0aDNcY2x3V2lkdGgxNTM2XGNscGFkZmIzXGNscGFkYjQ1XGNscGFkZmwzXGNscGFkbDQ1XGNscGFkZnIzXGNscGFkcjQ1XGNscGFkZnQzXGNscGFkdDQ1XGNlbGx4LTE1XGNsdmVydGFsY1xjbGJyZHJ0XGJyZHJub25lXGNsYnJkcmxcYnJkcm5vbmVcY2xicmRyYlxicmRybm9uZVxjbGJyZHJyXGJyZHJub25lXGNsdHhscnRiXGNsZnRzV2lkdGgzXGNsd1dpZHRoMjgwM1xjbHBhZGZiM1xjbHBhZGI0NVxjbHBhZGZsM1xjbHBhZGw0NVxjbHBhZGZyM1xjbHBhZHI0NVxjbHBhZGZ0M1xjbHBhZHQ0NVxjZWxseC01XHJvd1x0cm93ZFxpcm93Mlxpcm93YmFuZDJcbGFzdHJvd1x0cmxlZnQtNDVcdHJmdHNXaWR0aDNcdHJ3V2lkdGg5NjMyXHRibGluZHR5cGUzXHRibGluZDBcY2x2ZXJ0YWxjXGNsYnJkcnRcYnJkcm5vbmVcY2xicmRybFxicmRybm9uZVxjbGJyZHJiXGJyZHJub25lXGNsYnJkcnJcYnJkcm5vbmVcY2x0eGxydGJcY2xmdHNXaWR0aDNcY2x3V2lkdGgxODQyXGNscGFkZmIzXGNscGFkYjQ1XGNscGFkZmwzXGNscGFkbDQ1XGNscGFkZnIzXGNscGFkcjQ1XGNscGFkZnQzXGNscGFkdDQ1XGNlbGx4LTM1XGNsdmVydGFsY1xjbGJyZHJ0XGJyZHJub25lXGNsYnJkcmxcYnJkcm5vbmVcY2xicmRyYlxicmRybm9uZVxjbGJyZHJyXGJyZHJub25lXGNsdHhscnRiXGNsZnRzV2lkdGgzXGNsd1dpZHRoMzQ1MVxjbHBhZGZiM1xjbHBhZGI0NVxjbHBhZGZsM1xjbHBhZGw0NVxjbHBhZGZyM1xjbHBhZHI0NVxjbHBhZGZ0M1xjbHBhZHQ0NVxjZWxseC0yNVxjbHZlcnRhbGNcY2xicmRydFxicmRybm9uZVxjbGJyZHJsXGJyZHJub25lXGNsYnJkcmJcYnJkcm5vbmVcY2xicmRyclxicmRybm9uZVxjbHR4bHJ0YlxjbGZ0c1dpZHRoM1xjbHdXaWR0aDE1MzZcY2xwYWRmYjNcY2xwYWRiNDVcY2xwYWRmbDNcY2xwYWRsNDVcY2xwYWRmcjNcY2xwYWRyNDVcY2xwYWRmdDNcY2xwYWR0NDVcY2VsbHgtMTVcY2x2ZXJ0YWxjXGNsYnJkcnRcYnJkcm5vbmVcY2xicmRybFxicmRybm9uZVxjbGJyZHJiXGJyZHJub25lXGNsYnJkcnJcYnJkcm5vbmVcY2x0eGxydGJcY2xmdHNXaWR0aDNcY2x3V2lkdGgyODAzXGNscGFkZmIzXGNscGFkYjQ1XGNscGFkZmwzXGNscGFkbDQ1XGNscGFkZnIzXGNscGFkcjQ1XGNscGFkZnQzXGNscGFkdDQ1XGNlbGx4LTVccGFyZFxwbGFpblxxbFxpbnRibHtcYlxmMVxmczIyXGNmMCBSRUZFUlJFRCBCWX1cZjFcZnMyMlxjZjBcY2VsbFxwYXJkXHBsYWluXHFsXGludGJse1xmMVxmczIyXGNmMCA6IFx7UkVGRVJSQUxET0NUT1JcfX1cZjFcZnMyMlxjZjBcY2VsbFxwYXJkXHBsYWluXHFsXGludGJse1xiXGYxXGZzMjJcY2YwIFJFUC4gREFURX1cZjFcZnMyMlxjZjBcY2VsbFxwYXJkXHBsYWluXHFsXGludGJse1xmMVxmczIyXGNmMCA6IFx7UkVQT1JUUFJJTlRFRFRJTUVcfX1cZjFcZnMyMlxjZjBcY2VsbFx0cm93ZFxpcm93Mlxpcm93YmFuZDJcbGFzdHJvd1x0cmxlZnQtNDVcdHJmdHNXaWR0aDNcdHJ3V2lkdGg5NjMyXHRibGluZHR5cGUzXHRibGluZDBcY2x2ZXJ0YWxjXGNsYnJkcnRcYnJkcm5vbmVcY2xicmRybFxicmRybm9uZVxjbGJyZHJiXGJyZHJub25lXGNsYnJkcnJcYnJkcm5vbmVcY2x0eGxydGJcY2xmdHNXaWR0aDNcY2x3V2lkdGgxODQyXGNscGFkZmIzXGNscGFkYjQ1XGNscGFkZmwzXGNscGFkbDQ1XGNscGFkZnIzXGNscGFkcjQ1XGNscGFkZnQzXGNscGFkdDQ1XGNlbGx4LTM1XGNsdmVydGFsY1xjbGJyZHJ0XGJyZHJub25lXGNsYnJkcmxcYnJkcm5vbmVcY2xicmRyYlxicmRybm9uZVxjbGJyZHJyXGJyZHJub25lXGNsdHhscnRiXGNsZnRzV2lkdGgzXGNsd1dpZHRoMzQ1MVxjbHBhZGZiM1xjbHBhZGI0NVxjbHBhZGZsM1xjbHBhZGw0NVxjbHBhZGZyM1xjbHBhZHI0NVxjbHBhZGZ0M1xjbHBhZHQ0NVxjZWxseC0yNVxjbHZlcnRhbGNcY2xicmRydFxicmRybm9uZVxjbGJyZHJsXGJyZHJub25lXGNsYnJkcmJcYnJkcm5vbmVcY2xicmRyclxicmRybm9uZVxjbHR4bHJ0YlxjbGZ0c1dpZHRoM1xjbHdXaWR0aDE1MzZcY2xwYWRmYjNcY2xwYWRiNDVcY2xwYWRmbDNcY2xwYWRsNDVcY2xwYWRmcjNcY2xwYWRyNDVcY2xwYWRmdDNcY2xwYWR0NDVcY2VsbHgtMTVcY2x2ZXJ0YWxjXGNsYnJkcnRcYnJkcm5vbmVcY2xicmRybFxicmRybm9uZVxjbGJyZHJiXGJyZHJub25lXGNsYnJkcnJcYnJkcm5vbmVcY2x0eGxydGJcY2xmdHNXaWR0aDNcY2x3V2lkdGgyODAzXGNscGFkZmIzXGNscGFkYjQ1XGNscGFkZmwzXGNscGFkbDQ1XGNscGFkZnIzXGNscGFkcjQ1XGNscGFkZnQzXGNscGFkdDQ1XGNlbGx4LTVccm93XHBhcmRccGxhaW5ccWxcZjFcZnMyMlxjZjBccGFyfVxwYXJkXHBsYWluXHFsXGZzMjJcY2YwXHBhcn0";
    const rtfContent = base64ToRtf(base64String);
    const modifiedRtfContent = replacePatientName(rtfContent, targetName);
    const modifiedBase64String = this.rtfToBase64(modifiedRtfContent);

    return modifiedBase64String;
  }
}
